### ISSUE TITLE
For events add support for physical web information

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#165]
Imagine each GDG has a uriBeacon (https://github.com/google/uribeacon) and places it at the location/building of the event on the day of the event. Attendees of the event get then through the uriBeacon a direct link to the event when they enter the location/building.

The uri is be the gdg.events url of the chapter.

The organizer can enable uriBeacon support for their events on the hub page.

Frisbee supports deep linking from this uri to the current event, i.e. the event of today.

**Comment by tasomaniac** [comment]
I think we should have a events section in the application. Or we can even have a separate application (iosched fork) for GDG events. 

In the DevFest session, all the GDGs used iosched fork for their events. We used www.conferenceengineer.com for GDG DevFest Istanbul. It was really helpful. We converted the schedule data we build for Project Zeppelin. 

I think we should have common GDG Event Scheduler application that gets the data from GDG[X] hub. The idea here is great and it will be logical if we have this in that application. Iosched 2014 has also beacon support. We can modify it to make use of it.

**Comment by friedger** [comment]
Currently, the hub and developers.google.com does not support any kind of
agenda. This is a prerequisit to get a scheduler app like iosched clone.

Maybe we can convince Al to merge conferenceengineer into the hub :-)


  [image: --]
Friedger Müffke
[image: http://]about.me/friedger
<http://about.me/friedger>


2015-01-11 21:38 GMT+01:00 Said Tahsin Dane <notifications@github.com>:

**Comment by tasomaniac** [comment]
I wish. :) Do you think we can?

**Comment by friedger** [comment]
I am closing this and add an issue for this general use case independent of the technology

**Comment by friedger** [comment]
See https://github.com/gdg-x/frisbee/issues/531

**Comment by tasomaniac** [comment]
Makes sense to close it. 
We have deep linking support for event links. If those links are written into beacons, they will I think open the app right?
