### ISSUE TITLE
Integrate with Google Now

### ISSUE THREAD

**Issue by mauimauer** [gdg-x/frisbee#168]
See: http://insidesearch.blogspot.com.tr/2015/01/google-app-update-get-now-cards-from.html

**Comment by friedger** [comment]
@mauimauer Do you see any possibility that this is gonna happen?

**Comment by friedger** [comment]
@mauimauer Could you get us into the preivew program?

**Comment by mauimauer** [comment]
I am not working with Devrel so I recommend asking @keyboardsurfer

**Comment by tasomaniac** [comment]
Yes, @keyboardsurfer enlight us. :)

**Comment by keyboardsurfer** [comment]
I'm not able to do anything as of now. The article mentions that "we plan to add more cards and expand this feature over time". Anyhow, what is it you want to achieve with the Google Now integration? This issue looks like "integrate for integration's sake" to me.

**Comment by tasomaniac** [comment]
Upcoming events of a chapter?

We have a DashClock extension for upcoming events and it is working really great. But since widgets on lockscreen are gone now, usage of DashClock dropped.

**Comment by tasomaniac** [comment]
I will go ahead and close this since the Google Now API is not public. Please feel free to open it if you think we can do this.
