### ISSUE TITLE
Replace ViewPagerIndicator with new PagerTitleStrip

### ISSUE THREAD

**Issue by HenriqueRocha** [gdg-x/frisbee#170]
## Problem

Currently we're using JakeWarton's ViewPagerIndicator which is somewhat deprecated in terms of design.

![viewpagerindicator](https://cloud.githubusercontent.com/assets/140122/6250979/21121126-b789-11e4-8476-88bf5c473328.png)

## Proposed solution

Replace ViewPagerIndicator with the more recent UI used in the Materialized apps:

![slidingtabs](https://cloud.githubusercontent.com/assets/140122/6251014/4d6706dc-b789-11e4-9cda-50d6a2623eab.png)

**Comment by HenriqueRocha** [comment]
I can work on this if no one has any objection.

**Comment by friedger** [comment]
Let the Pull Requests coming :-)

**Comment by tasomaniac** [comment]
This would be a great improvement.

**Comment by HenriqueRocha** [comment]
I already did some work on this but I'm having some trouble in the activities which change the view pager indicator contents after it sets the pager in it. I'll have to figure out how to fix that.
I'm using SlidingTabLayout and SlidingTabStrip from the iosched app.
You can check in my feature/replace-viewpagerindicator branch if you want.

**Comment by HenriqueRocha** [comment]
My work on this issue is finally finished. Since I left the branch on hold for a while the rebase caused a lot of conflicts. I'm going to clean up a bit and create a PR. One step closer to Materializing the app. :+1:

**Comment by HenriqueRocha** [comment]
This should be closed when #207 is merged.
