### ISSUE TITLE
Replace cards where they should not be used

### ISSUE THREAD

**Issue by HenriqueRocha** [gdg-x/frisbee#171]
Since now there are guidelines for when to use cards, I propose that cards should be replaced with tiles where relevant. For example, in the grid of contributors and GDEs.
It will make the app more visually appealing IMHO.
I can work on this issue on my free time if no one has anything against it since it looks like a fairly straightforward change.

**Comment by friedger** [comment]
All contributions are welcome.


  [image: --]
Friedger Müffke
[image: http://]about.me/friedger
<http://about.me/friedger>


2015-02-04 17:42 GMT+01:00 Henrique Rocha <notifications@github.com>:

**Comment by tasomaniac** [comment]
Cards are not in a perfect shape right now but there are other issues about redesign. `card_bg` png asset is deleted. So we should close this issue. Any objection?
Closed via #340
