### ISSUE TITLE
Chorest / Checkstyle integration

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#173]
I love this integration. 
https://gradle.org/docs/current/userguide/checkstyle_plugin.html

As the number of contributers to the app is growing, how many people think that we should have something like this to have the same style consistency in the code. 

Since the codebase is already big, it will be hard to apply all the checkstyle but we can have some eg location of the curly brackets, parentheses locations.

**Comment by HenriqueRocha** [comment]
:+1:

**Comment by mauimauer** [comment]
+1

**Comment by stefanhoth** [comment]
Unfortunately the out-of-the-box integration doesn't work with the android-gradle plugin.

The workaround is to create a custom task that uses the plugin's classes as described here: 
[Blog post](http://qvdev.github.io/android/2014/02/24/android-gradle-static-analyzers.html)

I asked the tools team last week [G+ post](https://plus.google.com/111333123856542807695/posts/LN3Be44BQe7) and the status is still the same.

**Comment by tasomaniac** [comment]
But still, it is not hard to do. We are using it and it is really helpful.

You just add a task into the main build.gradle file. And that define build
depends on checkstyle.

The problem is when we integrate it, there will be lots of things to fix.
And it is not very fun thing to do :)

**Comment by stefanhoth** [comment]
Yes, I didn't want to shoot you down, just saying that it's a bit more work than "apply plugin".

If you have time, you can go for it.

**Comment by tasomaniac** [comment]
fixed via #275
