### ISSUE TITLE
Remove license text from individual files

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#182]
Remove all license text from individual files that has been created by this project.

**Comment by HenriqueRocha** [comment]
Instead of removing, shouldn't we just create one single commit that updates the copyright of all the files?
It's a pretty straightforward "replace all".

**Comment by tasomaniac** [comment]
Should we close this?

**Comment by HenriqueRocha** [comment]
@friedger This can also be closed since you've already merged #187 :+1:
