### ISSUE TITLE
Create auto-updates for the Alpha Channel

### ISSUE THREAD

**Issue by stefanhoth** [gdg-x/frisbee#185]
Since the release of the [HTTP Upload API for the Play Store](https://developers.google.com/android-publisher/) we can automate the release of builds into the Play Store.

As a start we could use the Alpha Channel to upload successful builds of the develop branch. I'd suggest to allow the GDG Sandbox community to be alpha testers.

For easy integration we could use [this gradle plugin](https://github.com/Triple-T/gradle-play-publisher) by using [Travis encryption](http://docs.travis-ci.com/user/encrypting-files/) to not leak private information like a Play Store API key.

**Comment by tasomaniac** [comment]
Great idea. This can be a blog post as well, once it is done. It would be a great example.

**Comment by HenriqueRocha** [comment]
:+1:

**Comment by tasomaniac** [comment]
There is a plugin for Jenkins to do this after a build but I couldn't find for Travis. We can use that gradle plugin though.

**Comment by stefanhoth** [comment]
It should be part of the build, not the build server. So I'd prefer to have it in gradle anyway. :smile:

**Comment by tasomaniac** [comment]
makes sense. :100:

**Comment by friedger** [comment]
added in https://github.com/gdg-x/frisbee/commit/34691e912d25bc276abd1fca1e8029b0fa2cb5d1

So it is now just a question of configuration

**Comment by stefanhoth** [comment]
@friedger are you able to provide the credentials I need to prepare this?

**Comment by tasomaniac** [comment]
I've just read this post via Android Weekly and wanted to share with all of you guys. 
http://www.bignerdranch.com/blog/continuous-delivery-for-android/

**Comment by mauimauer** [comment]
We could see if building on a Jenkins in the GDG[x] Cloud is
feasible/possible

2015-03-09 9:16 GMT+00:00 Said Tahsin Dane <notifications@github.com>:

**Comment by tasomaniac** [comment]
This is actually done in #539
