### ISSUE TITLE
Define constants to use for putting and retrieving arguments

### ISSUE THREAD

**Issue by ViliusKraujutis** [gdg-x/frisbee#189]
In my company's A-Team, we always define constants for putting and retrieving values from `getArguments()`.

I've noticed it's not practiced here: https://github.com/gdg-x/frisbee/pull/188#discussion_r24403811

I'd like to fix this. What do you think guys if (e.g. in [this file](https://github.com/HenriqueRocha/frisbee/blob/feature/186_pull_to_refresh/app/src/main/java/org/gdg/frisbee/android/fragment/GdlListFragment.java)) instead of:
```
arguments.putString("category", cat);
getArguments().getString("category")
```
would be:
```
private static final String ARGS_KEY_CATEGORY = "category"
arguments.putString(ARGS_KEY_CATEGORY, cat);
getArguments().getString(ARGS_KEY_CATEGORY)
```

**Comment by HenriqueRocha** [comment]
:+1:

**Comment by friedger** [comment]
Assigned to @ViliusKraujutis :-)

**Comment by ViliusKraujutis** [comment]
:+1:

**Comment by friedger** [comment]
Yes, keep the Pull Requests coming. This is a community effort.
