### ISSUE TITLE
Choose between Volley or Picasso for image loading

### ISSUE THREAD

**Issue by HenriqueRocha** [gdg-x/frisbee#190]
Right now the app uses both Volley and Picasso for image loading.
Which one do you think we should use and why?
I'll remove the one we exclude.

**Comment by friedger** [comment]
Volley is used for the API calls, hence, I suggest to remove Picasso.


  [image: --]
Friedger Müffke
[image: http://]about.me/friedger
<http://about.me/friedger>


2015-02-11 0:08 GMT+01:00 Henrique Rocha <notifications@github.com>:

**Comment by tasomaniac** [comment]
I don't like how Volley handles image loading personally. There are even
libraries that make it look like Picasso api. Picasso is really lightweight
to use.

**Comment by friedger** [comment]
What do you don't like in particular? We can write a wrapper if needed or
so. We only need default behavior...
Am 11.02.2015 10:00 schrieb "Said Tahsin Dane" <notifications@github.com>:

**Comment by HenriqueRocha** [comment]
I also don't like Volley's API for dealing with images but I believe that removing one of them will probably end the out of memory errors that I sometimes get. I suppose it's because the app is using two different bitmap caches.

**Comment by mauimauer** [comment]
I would encourage a move to OkHttp + Retrofit + Picasso, for Image Loading and all other API implementations.

**Comment by HenriqueRocha** [comment]
:+1: to use Square libs

**Comment by HenriqueRocha** [comment]
Pull request #192 should close this issue by moving to Picasso.
