### ISSUE TITLE
Background problem. 

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#193]
As you can see in this link, one of the 9 patch backgrounds are broken. I am using Nexus 6. I think it is also the same when I use LG g3. 

![image](https://cloud.githubusercontent.com/assets/45467/6316523/58fe3414-ba29-11e4-81f6-deff90900357.png)

**Comment by stefanhoth** [comment]
@tasomaniac Github supports inline images, even upload via copy&paste. Hope you don't mind correcting your issue.

**Comment by tasomaniac** [comment]
No problem. I think I created this issue on Github Android App. That's why it was like that.

**Comment by friedger** [comment]
Is this issue still valid?

**Comment by tasomaniac** [comment]
I cannot check it because the info page does not open because I don't have
the keys :(
It is still like this on the play store build.

**Comment by tasomaniac** [comment]
Update on this issue: 
I have the keys now and I opened the app with the latest development branch. 
The portrait mode is replaced with support library cards. But the landscape mode is still the same. 

If we replace all places with new cards, this issues will be closed. 
But there is a new problem now. Because of the paddings, new cards look really ugly. :crying_cat_face:

**Comment by friedger** [comment]
We have an issue about the padding. Closing this one.

**Comment by friedger** [comment]
This is the related issue https://github.com/gdg-x/frisbee/issues/237

**Comment by tasomaniac** [comment]
Makes sense.
