### ISSUE TITLE
Use IO Extended as special events

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#211]
The special events should be updated for IO extended 2015 events

**Comment by tasomaniac** [comment]
Or Android Study Jams? Or Women Techmakers? We can do extended after study
Jams.

**Comment by friedger** [comment]
In the long term, we just change the data on the hub.

Is there WTM happening globally? What is the time frame?

I can imagine to promote events on the main activity/chapter page either on
a regional level or chapter level. Again this should probably happen
through the hub.

As 2.0 will be hopefully released in mid/end march, study jam has partly
finished and it is 8 weeks before io extended, good enough to start
promoting it...




  [image: --]
Friedger Müffke
[image: http://]about.me/friedger
<http://about.me/friedger>


2015-02-23 6:43 GMT+01:00 Said Tahsin Dane <notifications@github.com>:

**Comment by tasomaniac** [comment]
If we release the 2.0 at that time, it will be too late for Study Jams. WTM
events will happen during March. And yes it is global. Just like DevFest's
but not that big.

**Comment by friedger** [comment]
So lets get a version ready for tag "wtm", probably best a branch from the currently released version, only with the special events updated.

**Comment by friedger** [comment]
Super powers ☺
Am 25.02.2015 13:00 schrieb "Said Tahsin Dane" <notifications@github.com>:

**Comment by tasomaniac** [comment]
:smile: :battery:
