### ISSUE TITLE
Replace Holo theme with Material theme

### ISSUE THREAD

**Issue by HenriqueRocha** [gdg-x/frisbee#216]
## Problem
Currently the app still has legacy drawables of the Holo theme. Those are not necessary anymore by using the new Material theme.

## Proposed solution
Delete all the custom drawables that were generated for the Holo theme. Colors will be added automatically as part of the Material Theme by defining the appropriate primary and accent colors.

### Note
This will be done as part of #174 since a lot of work has already been done and this needs to be addressed to make sure that everything look correct.

**Comment by tasomaniac** [comment]
We have to be careful on this because Buttons are not included in AppCompat
support library. We shouldn't delete drawables for buttons

**Comment by HenriqueRocha** [comment]
Okay, I'll make sure that I don't break anything. I've just finished replacing the ActionBar with the Toolbar everywhere. It was a lot of work!
