### ISSUE TITLE
Drop support for SDK older than 16

### ISSUE THREAD

**Issue by HenriqueRocha** [gdg-x/frisbee#217]
While implementing the new navigation drawer and getting more familiar with the code base I noticed many places where we're using code which requires API 11 or 14, even tough we're supporting API 10.

Due to the nature of this app, maybe it would be interesting to see the usage distribution of active users among the different APIs and maybe drop support for everything below 16 in the next version.

I don't know who has access to the Developer Console to check this out. Maybe @mauimauer ?

**Comment by tasomaniac** [comment]
Finally :)

**Comment by mauimauer** [comment]
Around 93% are on ore above level 16. So I guess it's ok to move up now.

2015-02-24 12:02 GMT+00:00 Said Tahsin Dane <notifications@github.com>:

**Comment by HenriqueRocha** [comment]
Awesome, I'm going to change that.

**Comment by tasomaniac** [comment]
Don't do it. I already did it.
