### ISSUE TITLE
Open Login page with a description for things that require login.

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#222]
Instead of giving an error when the button is clicked, 

open the Login page with an information about the clicked button, the feature and why login is necessary.

**Comment by tasomaniac** [comment]
Can you assign this to me? ty

**Comment by HenriqueRocha** [comment]
@tasomaniac I can't assign to you. :(

**Comment by friedger** [comment]
Claiming by comment is the way to go as we would like to have contributions
from all over the world.
Am 24.02.2015 17:14 schrieb "Henrique Rocha" <notifications@github.com>:

**Comment by tasomaniac** [comment]
I am changing this to 2.2 because I think it is relatively important.
