### ISSUE TITLE
Add visual highlight to the material nav drawer

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#234]
There should be an image of the home gdg or just the logo of the app if no home gdg was selected.
The users account name should be visible as well.

**Comment by tasomaniac** [comment]
As you said before, I also think that there is no need for a user switcher. 
But having the account name and using that account name area for login would be great. Because right now, if a user skips at setup, they have to go to the settings.

**Comment by HenriqueRocha** [comment]
I worked on this today and will work more later today. Hopefully I'll be able to submit a PR for this.

**Comment by friedger** [comment]
Is the image not enough? What are your plans?


  [image: --]
Friedger Müffke
[image: http://]about.me/friedger
<http://about.me/friedger>


2015-03-01 18:13 GMT+01:00 Henrique Rocha <notifications@github.com>:

**Comment by HenriqueRocha** [comment]
@friedger The avatar of the user should be displayed also just like any other app that uses the drawer with login.
Another thing that I already did but still needs some touches is placing the status bar on top of the drawer.

**Comment by friedger** [comment]
Good, go ahead, but I think the user's avatar is not a must for 2.0


  [image: --]
Friedger Müffke
[image: http://]about.me/friedger
<http://about.me/friedger>


2015-03-01 22:06 GMT+01:00 Henrique Rocha <notifications@github.com>:

**Comment by HenriqueRocha** [comment]
Okay, I won't add it now then. I'll finish this and move to work on the CardViews which should be removed almost everywhere. I already did some work on that also.

**Comment by tasomaniac** [comment]
I did Event Fragment and thinking to finish evet detail and info today

**Comment by friedger** [comment]
closed by #333
