### ISSUE TITLE
Re-add help to the nav drawer

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#236]

**Comment by HenriqueRocha** [comment]
@friedger Why did you close this?

**Comment by friedger** [comment]
has been added in the commit referenced above.


  [image: --]
Friedger Müffke
[image: http://]about.me/friedger
<http://about.me/friedger>


2015-02-28 11:38 GMT+01:00 Henrique Rocha <notifications@github.com>:

**Comment by HenriqueRocha** [comment]
:+1:
