### ISSUE TITLE
Login with G+ results infinite loop when it fails

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#238]
When the user first uses the app and chooses to login with g+ then after the 3rd step the applications tries to sign in again and again but fails to get a token with the error "sign_in_required".

**Comment by tasomaniac** [comment]
I thought it was because of `hub_client_id` is missing. Because it fails to login and I've researched and found that it is caused when client id is wrong/missing.

**Comment by friedger** [comment]
fixed

**Comment by friedger** [comment]
but the experience for developers is still bad :-1:

**Comment by Splaktar** [comment]
I just hit this and I have a `hub_client_id` defined. Not sure that my key have been approved to be accepted by the Hub tho.

**Comment by tasomaniac** [comment]
When we are offline it makes an infinite loop too. But there was another
issue already about this.

**Comment by friedger** [comment]
fixed in da2f1b0d978cacd359f31f0a289d9e0e1563a7f7
