### ISSUE TITLE
App crashes when rotating device while loading Pulse

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#240]
GIVEN the user launches the app the first time (is this required?)
WHEN the user clicks on the nav drawer on pulse and rotates the device
THEN the pulse should be shown in the correct orientation

Currently, the following exception occurs

W/System.err(17508): java.io.IOException: Invalid name: org.gdg.frisbee.android.api.model.Pulse<java.lang.String,org.gdg.frisbee.android.api.model.PulseEntry>
W/System.err(17508): 	at org.gdg.frisbee.android.cache.ModelCache.readValueFromDisk(ModelCache.java:637)
W/System.err(17508): 	at org.gdg.frisbee.android.cache.ModelCache.getFromDiskCache(ModelCache.java:339)
W/System.err(17508): 	at org.gdg.frisbee.android.cache.ModelCache.get(ModelCache.java:319)
W/System.err(17508): 	at org.gdg.frisbee.android.cache.ModelCache$1.doInBackground(ModelCache.java:272)
W/System.err(17508): 	at org.gdg.frisbee.android.cache.ModelCache$1.doInBackground(ModelCache.java:268)
W/System.err(17508): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
W/System.err(17508): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err(17508): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err(17508): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err(17508): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err(17508): 	at java.lang.Thread.run(Thread.java:818)

**Comment by tasomaniac** [comment]
This does not happen to me. Can you reproduce this easily?

**Comment by tasomaniac** [comment]
Actually, in line ModelCache.java:637, it converts ClassCastException into an IOException. It occurs because it couldn't find class `org.gdg.frisbee.android.api.model.Pulse`? Why do think that happens?

**Comment by tasomaniac** [comment]
@friedger  I was looking into this issue. I will fix an issue from the ModelCache that probably causes this. 
Bu I now realized that the above stacktrace only contains Warnings.

**Comment by friedger** [comment]
Can't reproduce

**Comment by Splaktar** [comment]
I cannot reproduce either.
