### ISSUE TITLE
Redesign event series activity

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#243]

**Comment by tasomaniac** [comment]
Thank you. It is almost finished.

**Comment by friedger** [comment]
I thought so and just wanted to make it more visible that you are working
on it.


  [image: --]
Friedger Müffke
[image: http://]about.me/friedger
<http://about.me/friedger>


2015-02-28 10:32 GMT+01:00 Said Tahsin Dane <notifications@github.com>:

**Comment by tasomaniac** [comment]
Thank you

**Comment by friedger** [comment]
implemented in #265
