### ISSUE TITLE
Improve access to Preferences

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#246]
Maybe remove "gdg" preferences and use DefaultSharedPreferences

or create an GDGPreferenceObject that wraps the "gdg" preferences

**Comment by mauimauer** [comment]
But beware: you might want to have a proper migrate function (ie. on versionCode jump, move settings out of the old pref instance) or this might screw things up

**Comment by friedger** [comment]
Do you have a motivation for using "gdg" instead of the default ones?
I don't care if it is only in on place defined.

**Comment by tasomaniac** [comment]
I think we can continue using "gdg" as the preferences. The problem was I
think manually writing "gdg" string everytime we use. If we can have a
utility class that controls sharwdprefs, isn't it enough?

**Comment by friedger** [comment]
I don't like that we have to put the context in all static methods.

**Comment by mauimauer** [comment]
why not just extract the "gdg" string to our static constants file.
