### ISSUE TITLE
Update translations for Release 2.0

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#257]

**Comment by tasomaniac** [comment]
We are going to do it using Crowdin right? When should we upload the new strings?

**Comment by friedger** [comment]
I just uploaded the source (using crowdin-cli). @tasomaniac Do you have access  to the project? I don't know how to download the translations.

**Comment by tasomaniac** [comment]
I was a translator. I don't think I have access to download the
translations.

**Comment by Splaktar** [comment]
I believe that this was implemented in #315
