### ISSUE TITLE
Proposal: Rename "Arrow" to "Tagging Game"

### ISSUE THREAD

**Issue by stefanhoth** [gdg-x/frisbee#264]
Arrow was the internal project name for the tagging game inside of frisbee. My guess is that no one outside GDG-X can associate anything with that name.

I'll propose to change the name in the navigation to "Tagging game" or something else equally obvious.

Also I propose a corresponding icon change for the drawer navigation. Maybe this one?

![image](https://cloud.githubusercontent.com/assets/45467/6433840/978a6882-c079-11e4-89f0-ad64bdc756a3.png)
(via [iconmonstr](http://iconmonstr.com/puzzle-18-icon/) )

**Comment by mauimauer** [comment]
+1 for the name change...that icon though, kind of reminds me of MS Office 98

**Comment by tasomaniac** [comment]
I also like the latest icon. I think that arrow name is cool. 😎 let's try
to find another name that includes tag

**Comment by stefanhoth** [comment]
@mauimauer Right, we don't want to get near this association :smile:

**Comment by stefanhoth** [comment]
How about this as "people meet people"?

![image](https://cloud.githubusercontent.com/assets/45467/6438869/5f7dff68-c0cd-11e4-92d4-0f069d4153aa.png)
(again via [iconmonstr](http://iconmonstr.com/user-14-icon/) )

**Comment by stefanhoth** [comment]
Or this?
![](http://google.github.io/material-design-icons/social/svg/ic_people_24px.svg)

**Comment by HenriqueRocha** [comment]
:+1: for that social/people icon

**Comment by tasomaniac** [comment]
People I've met? Maybe?

Just like in the Google IO app.

**Comment by tasomaniac** [comment]
What is the last situation about this now? Do someone have something in mind as an alternative name?

**Comment by friedger** [comment]
I am happy with arrow
Am 29.04.2015 14:53 schrieb "Said Tahsin Dane" <notifications@github.com>:

**Comment by tasomaniac** [comment]
I really like it too.

**Comment by erickmendonca** [comment]
I liked it, but I couldn't guess what it was before I tried it. 

:+1: to social icon

**Comment by tasomaniac** [comment]
We have now gamepad icon for the Arrow. It both looks like a game and look
like arrows :) I think it is good.

**Comment by erickmendonca** [comment]
Oh, great! I'll test it :)

**Comment by tasomaniac** [comment]
This one is used ![](https://github.com/gdg-x/frisbee/blob/develop/app/src/main/res/drawable-xxhdpi/ic_drawer_arrow.png)

**Comment by HenriqueRocha** [comment]
This issue is already a bit old. How should we proceed from here?

**Comment by tasomaniac** [comment]
If we have a poll, I would vote for the old name "Arrow". :smile:
