### ISSUE TITLE
Redesign InfoFragment

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#269]
InfoFragment now uses cards in portrait layout. 
It still uses old 9patch cards in landscape. 

Both of them are ugly and should be fixed.

**Comment by mauimauer** [comment]
Also paddings/margins seem a little screwed up.

**Comment by mauimauer** [comment]
![screenshot_2015-03-02-23-03-27](https://cloud.githubusercontent.com/assets/555852/6452893/b0e47ee6-c130-11e4-9ebb-c3686607a710.png)
Nexus 6

**Comment by tasomaniac** [comment]
Yep. That is the problem with all of the new card view usages in the app.

**Comment by PareshMayani** [comment]
@tasomaniac @mauimauer that padding issue has already been resolved in my pull request https://github.com/gdg-x/frisbee/pull/308 :)

**Comment by tasomaniac** [comment]
Landscape should be fixed. :) And keyline rythm should be followed. 

- All the body text should use keyline1 padding. 
- Organizer photos should have keyline1 padding. 
- Organizer names should have keyline2 padding from the left.

**Comment by tasomaniac** [comment]
I will close this issue since it is way much better now. 
Closed via #437
