### ISSUE TITLE
Redesign EventDetail page.

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#270]
Improve the use of card views in EventDetail.

**Comment by PareshMayani** [comment]
I am working on this issue and have made improvements.

Can you please check the these snaps and let me know if any changes are required?

1st improvement: Where I have done layout improvements.
![screenshot_2015-03-20-00-37-29](https://cloud.githubusercontent.com/assets/888080/6746436/2e578d62-ceee-11e4-944d-08d4e8c98c25.png)

2nd improvement: Where I have removed that resource background from description layout and have used CardView, to make it looks neat and clean. It would also make all the description layouts consistent across the app.

![screenshot_2015-03-20-11-55-43](https://cloud.githubusercontent.com/assets/888080/6746994/5c651b48-cef8-11e4-8996-6ea8877be2e7.png)

Please let me know if I should commit these improvements and pull the request :)

**Comment by tasomaniac** [comment]
Can you align the text inside the card and the texts in the header. Thank you. Great work.

**Comment by PareshMayani** [comment]
Done.

![screenshot_2015-03-21-02-44-30](https://cloud.githubusercontent.com/assets/888080/6760991/6102eed8-cf74-11e4-8a6b-29d48bb5e77a.png)

**Comment by friedger** [comment]
Closing this as it is not very actionable.

**Comment by tasomaniac** [comment]
This can be a label for other Event Detail page related issues. Like `Event Detail`
We have so much thing to do to improve that page.

**Comment by friedger** [comment]
nice, for the label. I would use component instead of epic.

**Comment by tasomaniac** [comment]
makes sense. changing it now.
