### ISSUE TITLE
Add in-app feedback option

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#274]
Add a library where users can give feedback from within the app when a crash occurs.

**Comment by friedger** [comment]
Something like instabug?

**Comment by mauimauer** [comment]
And not necessarily on crash. I was suggesting a Feedback Feature that allows the user to take a screenshot of the current screen (maybe even annotate it), write 1-2 lines and then send it. Very much like most of the Google Apps on Android do.

**Comment by mauimauer** [comment]
Maybe sth. like http://www.apptentive.com/
Has anyone worked with one of those services before? Suggestions?

**Comment by friedger** [comment]
I am looking at Doorbell.io: simple and one feature implemented (hopefully) right

**Comment by friedger** [comment]
doorbell is integrated. Let the discussion continue

**Comment by tasomaniac** [comment]
I actually liked doorbell and it is free and simple

**Comment by mauimauer** [comment]
I'm happy with doorbell...just to be perfectly honest, I would have preferred a little bit more time and discussion before actually settling on a 3rd party service.

**Comment by friedger** [comment]
It is not settled :-) think agile.


  [image: --]
Friedger Müffke
[image: http://]about.me/friedger
<http://about.me/friedger>


2015-03-04 1:03 GMT+01:00 Sebastian Mauer <notifications@github.com>:

**Comment by mauimauer** [comment]
Well, of course we could go ahead discuss again and then throw away a perfectly good albeit not really discussed implementation. But in my opinion this would be wasteful, not agile.

**Comment by tasomaniac** [comment]
We already implemented this but I recently found this library and its great implementation in U2020 app. 
https://github.com/mattprecious/telescope
https://github.com/JakeWharton/u2020/pull/93/files

These guys are awesome. They include recent debug logs in the system and screenshots into the feedback report. 

One difference is that they included it only into their dogfood releases not into the release.

**Comment by mauimauer** [comment]
Love the screenshot functionality...but I don't really see any reason why we shouldn't include it in prod releases as well (ie. we need all the feedback we can get).

**Comment by tasomaniac** [comment]
I looked at the library one more time. They say in the README that it is designed for dogfood builds. With this library whatever screen the users are, they can bug report with a screenshot of that screen with a gesture. 

And they include system  logs into the report. They are stripped in the release builds. 

Overall, it's a great library from a guy from Square Inc.
