### ISSUE TITLE
Toolbar Spinner is black on < Lollipop

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#283]
Here is the screenshot from Kitkat device

![screen shot 2015-03-03 at 23 57 01](https://cloud.githubusercontent.com/assets/763339/6473286/19f986e4-c201-11e4-95ec-f619db416f79.png)

**Comment by PareshMayani** [comment]
Looks like this issue is already been resolve as I can see White spinner handle.

**Comment by tasomaniac** [comment]
Which version are you using. This screen was taken on Kitkat using the latest production.

**Comment by PareshMayani** [comment]
Lollipop 5.0.2

**Comment by tasomaniac** [comment]
I now have a different behavior. I don't know how it changed. I may change it during theme refactorings but I don't think so. 

The behavior on KitKat is now like below. 

![screen shot 2015-04-29 at 14 44 45](https://cloud.githubusercontent.com/assets/763339/7390222/69ccb796-ee7e-11e4-9fa2-51f862c5fcf5.png)
