### ISSUE TITLE
User feedback: Colour/theme of Women Techmakers is a bit too bright and kind of painful on the eyes

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#287]
From Anne Olvido:

maybe better to use a cooler shade of green? I understand you used a colour picker on the Women Techmakers logo, took the liberty of tweaking the current layout
![screen shot 2015-03-04 at 10 23 26 pm](https://cloud.githubusercontent.com/assets/1449049/6487348/f369ce5e-c290-11e4-820c-2480c575ad71.png)

**Comment by tasomaniac** [comment]
She is right, I got the color from the logo. But thats me, I am not a
developer :) What should be the color code?

**Comment by mauimauer** [comment]
Use the one she used in the revised screenshot. (ie. use color picker on toolbar)
:cocktail:

**Comment by tasomaniac** [comment]
There are 2 colors for every event. primary and primaryDark. Actually
primaryDark can be generated dynamically and it is nor right now :)
