### ISSUE TITLE
User feedback: Cannot install on (Xiaomi) Mi Pad

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#288]
From Anne Olvido:
not sure if this is restricted to other tablets as well, might be gaood to check?

**Comment by tasomaniac** [comment]
That is probably because of this configuration. We shouldn't use this. Does anyone know why this is included?

```
  <supports-screens
    android:largeScreens="true"
    android:normalScreens="true"
    android:smallScreens="true"
    android:xlargeScreens="true" />
```

**Comment by tasomaniac** [comment]
We can remove this and update the alpha channel and make her try again.

**Comment by tasomaniac** [comment]
I am not 100% sure. We should confirm that with Anne
