### ISSUE TITLE
App Indexing

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#317]
App Indexing is perfect for GDG app. 
https://developers.google.com/app-indexing/

We should integrate it. We can add tags for the indexing into the https://github.com/gdg-x/balloon project.

**Comment by Splaktar** [comment]
Absolutely!

**Comment by erickmendonca** [comment]
:+1: 
This would make the app even more useful!

**Comment by friedger** [comment]
We can index
- the chapter page (MainActivity) and 
- the event page (EventActivity)

Does anything else make sense? The Pulse page, the GDE page?

**Comment by friedger** [comment]
started in branch https://github.com/gdg-x/frisbee/tree/feature/app_indexing

**Comment by tasomaniac** [comment]
I wish we could do Pulse page. But we would need our own implementation of the Pulse webpage. It's because we cannot add metadata to developers.google.com

I think we should use hub.gdgx.io for injecting metadata for search results because it both have events and chapter pages.

**Comment by mauimauer** [comment]
maybe we should also get in contact with DevRel, maybe connecting up with developer.google.com is possible after all.

**Comment by tasomaniac** [comment]
it would be really great to connect it with https://developer.google.com/groups
Who should we contact?

**Comment by mauimauer** [comment]
I'd suggest to bring this up at the Summit with Adriana or Martin

**Comment by tasomaniac** [comment]
Makes sense. Face to face discussion would be better. Thank you.

**Comment by friedger** [comment]
EventActivity can be index with http://gdgroups.org/<event id> like http://gdgroups.org/4729666051506176/

**Comment by friedger** [comment]
Started in https://github.com/gdg-x/frisbee/tree/feature/app_index

**Comment by friedger** [comment]
App Indexing was introduced in 2.3

**Comment by tasomaniac** [comment]
Doesn't this also include app indexing integration between the website and the app?
I mean when people search something in Google, and somehow found gdgroups.org link, if the app is not installed, Google will know the relation between the site and the app and will offer the user to install the app. And with the first openning of the app, that deeplinked page in the app will open. 

Like this: http://searchengineland.com/google-app-indexing-google-can-index-link-to-content-in-your-android-app-175692

**Comment by tasomaniac** [comment]
For example let's look at the following screenshot. 
From what I understand, this search should have Open In App button in the first result. I don't know how to do it but this issue covers this situation as well. 

![screenshot_20160127-131044](https://cloud.githubusercontent.com/assets/763339/12611851/90524732-c4f7-11e5-8b31-98fad0ebd662.png)

**Comment by friedger** [comment]
Then we should open a new issue for this particular part. I see this more in firefly than in frisbee. 

I like to have issues that are actionable :-)

**Comment by tasomaniac** [comment]
Isn't there anything left in Frisbee to achieve this? I think a separate issue would be nice. I just wanted to remind this part.
