### ISSUE TITLE
Clarify README to explain what the different keys are for and which are needed for debug builds

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/frisbee#329]
I'm trying to get the app to build locally and launch on my test device but this API key isn't explained in the README. The IP key (server key) is also not explained well enough.

The Wiki (https://github.com/gdg-x/frisbee/wiki/Developer-Documentation) says that the keys are in keys.xml but I cannot find that file in my project.

How do I know that my Hub key is valid?

**Comment by stefanhoth** [comment]
As of #231 the secrets have been moved to the local.properties file. The should be only relevant for building a release but I can see that the process/contributor setup is not really ideal right now.

**Comment by Splaktar** [comment]
Yep. I have entered what I can in my `local.properties` file, but I don't have access to things like the GCM sender key or the configuration needed to get the app to successfully log in on a development device. Thus I am not able to contribute.

**Comment by tasomaniac** [comment]
I don't think we need gcm sender key for development. The tricky part is
login, without login there are also parts to contribute. The app is working
without login.

**Comment by tasomaniac** [comment]
@PareshMayani has good amount of information about this. Can you update us with what you did to contribute to project? ty

**Comment by tasomaniac** [comment]
I think gcm_sender_id is not required for development. We should close this issue or rename it for something else. 

```
android_simple_api_access_key=
browser_simple_api_access_key=
ip_simple_api_access_key=
play_app_id=
```
are really easy to create. I think we can prepopulate them with key creates from a random app from a random account. 
```
android_backup_key=
gcm_sender_id=
```
are only needed for production. They are not needed for development and contribution. 

I don't know much about `hub_client_id=` though. Currently I cannot still sign in with the build with debug keystore.

**Comment by Splaktar** [comment]
From README: "`play_app_id` is the Google Developer Console project id".
This needs to say where a new contributor can get this `play_app_id` from (i.e. an existing Frisbee developer). I'm not sure why we can't just put this ID in the README?

How does a developer create a `ip_simple_api_access_key`? The other two seem obvious enough.

**Comment by Splaktar** [comment]
Looks like `ip_simple_api_access_key` is `Server key` in the Console. The README should make this a little more clear since the name is not that clear.

The `play_app_id` has to be the ID from the Frisbee Play Console which is hooked up to Google Play Games. You can't use the ID of your Cloud Console API project.

**Comment by Splaktar** [comment]
One more README update we just figured out. If there are unpublished Play Game Services updates, then all of the contributors need to be in the `Testing->Testing Access->Testers` list in the Play Games Console. This is because the version of the app they are running requires to unpublished Play Game updates which can only be seen by testers. 

A message like

    Application ID 10101010101 is not associated with package org.gdg.frisbee.android.debug

Indicates that this is the problem.

**Comment by friedger** [comment]
For reference, a more detailed description of the keys is in the wiki: 
https://github.com/gdg-x/frisbee/wiki/Developer-Documentation#configuration

**Comment by Splaktar** [comment]
We should probably move the Development stuff in the README.md to the CONTRIBUTING.md and link from the README to CONTRIBUTING explicitly.

**Comment by Splaktar** [comment]
OK, README.md Development section updated to just link to Dev Docs wiki and CONTRIBUTING.md (345f05c31a69f76ac9ba607d5918bf9b697916c4). Dev Docs in README.md moved to Dev Docs wiki (20bc04303db0ebbf169e83f037d3098c819102c9).

This should be all set now. Thank you to @friedger for the updates to the [Dev Docs](https://github.com/gdg-x/frisbee/wiki/Developer-Documentation) wiki to support this!
