### ISSUE TITLE
Drawer should have sections

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#336]
Right now our drawer is really crowded. Especially when there are more than 1 Special Event Series occuring in the world. 
So we should have sections in the drawer. At least for the settings/feedback/about.

**Comment by mauimauer** [comment]
Let me do this. Can use this patch to get approval for future contributions.

**Comment by tasomaniac** [comment]
:+1:

**Comment by HenriqueRocha** [comment]
@mauimauer What's the status of this? I'm working on the new NavigationView and I can add this as an extra if you want.

**Comment by friedger** [comment]
I don't think mauimauer does work on this one in the near future. So, go
ahead..
Am 14.06.2015 13:05 schrieb "Henrique Rocha" <notifications@github.com>:

**Comment by HenriqueRocha** [comment]
This will be done as part of issue #361

**Comment by tasomaniac** [comment]
This is closed automatically since @PareshMayani merged #410 
I will reopen it since the other parts are not sectioned yet.
