### ISSUE TITLE
Visual problems with Croutons

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#343]
Since we have `Toolbar` in the layout, `Croutons` are shown on top of the `Toolbar` which is really ugly. 

- [ ] If there is an error or info with nothing in the content area, remove `Crouton` and add the error as an empty view. 
- [x] If there is an error with a cached data to show, show the data and display the `Crouton` below `Toolbar` and tabs.

**Comment by mauimauer** [comment]
Fix it (ie. display them under the toolbar). Croutons are still way better than Toasts

**Comment by tasomaniac** [comment]
I was thinking to use empty central views for errors. I also think that we shouldn't use Toasts. 
Most of the Crouton messages can be done via empty views.

**Comment by mauimauer** [comment]
Not sure about empty views for that, there are cases when we have cached content that could be shown instead of an empty view. As a user I would prefer old/stale data and a transient error notification (crouton) instead of not having access to the data at all (empty view).

**Comment by tasomaniac** [comment]
I am not specifically talking about the cached content. There are also errors that actually does not show anything but a crouton.

**Comment by mauimauer** [comment]
And I just wanted to make sure all cases get handled properly. So I guess a mixture of Croutons and customized Empty Views would be the way to go.

**Comment by tasomaniac** [comment]
Sure. Thank you. :)

**Comment by tasomaniac** [comment]
Desc is updated.

**Comment by tasomaniac** [comment]
I will re-open an issue about empty views. We should have empty view states with error information I think.
