### ISSUE TITLE
Devices without GMS

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#355]
For devices without GMS we are showing the following Dialog saying that "App won't work without Play Services installed". App runs fine without GMS excepts for the "Arrow" and "Achivements"

- [ ] We may display that Dialog only 1 time. Showing it on every page is really bad. 
- [x] Sign-in button in Settings should be disabled with a message about GMS is not available. 

![screen shot 2015-05-08 at 22 11 07](https://cloud.githubusercontent.com/assets/763339/7543764/bd52a8c8-f5cf-11e4-9646-0b05ed9ed43c.png)

**Comment by friedger** [comment]
Related to https://github.com/gdg-x/frisbee/tree/fix/google_api

**Comment by tasomaniac** [comment]
I believe the 2nd portion is done. I am not sure about the first though. Why are we showing that "Get Play Services" dialog? That is dumb. When there is no play services on the device, it is unlikely that the user could install it. Let's remove that dialog completely? What do you say?

**Comment by friedger** [comment]
1st portion is not yet done.

How would you decide what to do on resolution error? Only check for SERVICE_MISSING? Started on https://github.com/gdg-x/frisbee/tree/355/no_gms

**Comment by friedger** [comment]
1st portion can only be fixed when #483 is fixed as the Plus client shows the mentioned dialog automatically.

**Comment by tasomaniac** [comment]
Are you sure that it shows it automatically? It gives the dialog to us and we show it using `showDialog` method.

**Comment by friedger** [comment]
Not after my changes

**Comment by tasomaniac** [comment]
Your changes already fixes the point 1 in this issue actually :)

**Comment by friedger** [comment]
But the dialog still appears

**Comment by tasomaniac** [comment]
It will make a huge difference if it only appear once. I think we can ignore that for now and we can open another issue for that if we want to remove it completely.

**Comment by tasomaniac** [comment]
Fixed by #582
