### ISSUE TITLE
Refactor: Achievements

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#358]
We should go over Achievements. We can easily add new achievements. And we can retire old achievements like Google Developers Live. 

It may include Achievements for
- GDE section
- Arrow (multiple achievements like if you are tagged 10, 20, 50, 100 etc people)
- Sending a feedback. 
- Added widget or DashClock extension. 
- Opened new links in the Leads page (like Wisdom etc. )

Please contribute for new ideas.

**Comment by friedger** [comment]
I still hope to have something like "Gave a talk at a GDG event" which would involve some kind of interaction between organizers and members via the Hub (:-P)

**Comment by Splaktar** [comment]
Those look like great ideas!

**Comment by tasomaniac** [comment]
@friedger that would be awesome, and we can actually have it as an achievement in Android App, if we have it in the Hub.

**Comment by tasomaniac** [comment]
Here are the new achievements. I think you guys can be more productive than me. :)
Let's find funny titles. 

6-7-8 are for meeting people more than 1-5-20 times respectively. 
9 for sending feedback
10 for adding the widget
11 for opening the GDG Wisdom book link

![screen shot 2015-05-21 at 00 57 32](https://cloud.githubusercontent.com/assets/763339/7737511/5cc9f1d0-ff54-11e4-9cab-d1bb48c5bc86.png)

**Comment by Splaktar** [comment]
It looks like this has to be finished or reverted before we can ship 2.2.

**Comment by tasomaniac** [comment]
We didn't publish the new Achievements. I actually implemented all of them. But I didn't test them.

**Comment by friedger** [comment]
The achievements are published.

**Comment by tasomaniac** [comment]
Most of the implementation is not working. We can finish the integration
before release.

**Comment by friedger** [comment]
What needs to be done to finish this?
