### ISSUE TITLE
Arrow tagging layout loses button, breaks send mode

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/frisbee#360]
After updating to the latest version, the arrow button is no longer there. This means that I can tap the screen and do a visual scan to tag others, but I am completely unable to allow others to tag me (scan mode).

I was able to get it back by reinstalling the app, but after I scanned someone else (Said) the button disappeared again. Logging out of G+ and back in does not fix it.

I was trying to get more people using the app and tagging each other now at the summit, but this is really breaking that :disappointed:

**Comment by tasomaniac** [comment]
Is it lost for you again. I hope we can find out and fix it here.

**Comment by Splaktar** [comment]
Yes, I can't seem to get it back without reinstalling the app.

**Comment by Splaktar** [comment]
This needs to get some attention.
