### ISSUE TITLE
Use new NavigationView

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#361]
Update the left nav drawer with the `NavigationView` from design support library.
Navigation drawer menu should have sections as required by #336

**Comment by HenriqueRocha** [comment]
I'll work on this tomorrow.

**Comment by HenriqueRocha** [comment]
In progress now.

**Comment by HenriqueRocha** [comment]
Apparently there are still bugs in the NavigationView regarding adding items dynamically to the groups in the drawer. I'll try to find a workaround while there isn't a proper solution. This is required because we add events dynamically.

**Comment by tasomaniac** [comment]
Is it a critical bug? If so, I would say lets not deal with it and use the old system. What is the situation?

**Comment by HenriqueRocha** [comment]
The problem is that I can't add items dynamically to a section in the navdrawer. I don't know if it's my problem, but I can't make it work. They are always added to the end.

**Comment by HenriqueRocha** [comment]
I will work on porting the rest of the design support library (DSL) during this week. Hopefully, all other issues regarding the DSL can be closed soon.

**Comment by PareshMayani** [comment]
I just pushed commit with the NavigationView improvement. Please take update and check!

@HenriqueRocha BTW, we can get Menu using navigationView.getMenu() and then using that object we can add items!

**Comment by PareshMayani** [comment]
Sorry Henrique, I have to complete the NavigationView part to proceed further using support library. As mentioned in the comment (https://github.com/gdg-x/frisbee/issues/373#issuecomment-120635959), I got the issue as soon as I declared support library and was not able to run the app!

**Comment by tasomaniac** [comment]
Fixed in #379

**Comment by PareshMayani** [comment]
@tasomaniac it's not completed yet as sections are yet to implement! Either this should be open or #336

**Comment by tasomaniac** [comment]
I think the other one should be reopened.
