### ISSUE TITLE
Replace Croutons with new Snackbar implementation.

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#365]
More info : http://developer.android.com/reference/android/support/design/widget/Snackbar.html

**Comment by PareshMayani** [comment]
Anyone is making this enhancement?

**Comment by friedger** [comment]
assigned to @PareshMayani :-)

**Comment by tasomaniac** [comment]
Nope. No one is working on this.
I've sorted out the Croutons. They are shown perfectly now. But they need
to be changed. As far as I remember there are few of them left. I have
changed 2 of them (asking logins) to Dialogs with Login button.

**Comment by PareshMayani** [comment]
@tasomaniac I didn't get about it:

"I've sorted out the Croutons. They are shown perfectly now. But they need to be changed.".

I guess I am missing something about the crouton implementation!

**Comment by tasomaniac** [comment]
I was talking about the issue #343 and the solution #353 
Croutons are designed to be displayed at top of the window below ActionBar. When Toolbar is included in the layout, Croutons started to be displayed on top of Toolbar. And they were ugly. 
I fixed that but now they have to be replaced with Snackbar's

**Comment by PareshMayani** [comment]
Would this implementation work? Please suggest if any change is required in snackbar styling :)

![device-2015-07-21-232054](https://cloud.githubusercontent.com/assets/888080/8808307/6b9ff3cc-2fff-11e5-8795-88596983d285.png)

**Comment by tasomaniac** [comment]
Looks really good to me.

**Comment by stefanhoth** [comment]
:+1: Noice!

**Comment by Splaktar** [comment]
Does it need to have a red background? Would red text on default background work or is red not needed at all? 

I have seen discussions lately about coloring toasts or snackbars being outside the spec.

**Comment by tasomaniac** [comment]
I think it looks great. We can go outside of the specs. 

But in general my opinion is that we don't need Toast or Snackbar for errors. For example if you look at the error here. It is on the first open of the app. The user cannot even pass this screen. Apps become unusable. 
For other GET request network errors, we should utilize the empty layout of the pages, instead of displaying a message with a timeout on a blank screen. 
For POST operations (which we don't have much) if the operation is important, I would say we can go for a `Dialog` instead of a Snackbar. If the operation is not that important, we can show a gray Snackbar.

**Comment by PareshMayani** [comment]
@Splaktar I had two ideas while implementing the snackbar:

1. Make the Snackbar looking same as Crouton
2. Or display the default snackbar but with different colors, say for example red for alert message.

So I went ahead with displaying snackbar with different background colors, just to make it same as Crouton, it's fine if we want to go beyond the specs. 

Or and otherwise, let's go with specs and have different colors for the message.

Let me know your final thoughts!

**Comment by PareshMayani** [comment]
@tasomaniac agree with your point that user should be able to see at least a home screen, but for that we will have to sync data in background, if network is available!

**Comment by tasomaniac** [comment]
Fixed by #384
