### ISSUE TITLE
Replace tabs with ViewPagers with TabLayout

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#366]
More info: http://developer.android.com/reference/android/support/design/widget/TabLayout.html

We can also possibly use [AppBarLayout](http://developer.android.com/reference/android/support/design/widget/AppBarLayout.html) in most of the places.

**Comment by PareshMayani** [comment]
@tasomaniac I think It's already fixed with your pull request #392.

**Comment by tasomaniac** [comment]
Fixed in #392

**Comment by tasomaniac** [comment]
thank you @PareshMayani
