### ISSUE TITLE
Issue: display order mismatch in GDE directory

### ISSUE THREAD

**Issue by PareshMayani** [gdg-x/frisbee#369]
There is a mismatch in displaying GDE profiles on web and mobile. Find attached snap and check.

BTW, it's not a perfect order on web I would say, it should either be in ascending or descending order. Existing GDE may report it to Google :)

![experts directory _ web](https://cloud.githubusercontent.com/assets/888080/8612970/15e3c37a-26f7-11e5-9137-d8bf5a5edce4.PNG)

![screenshot_2015-07-10-11-28-24](https://cloud.githubusercontent.com/assets/888080/8612978/26a62414-26f7-11e5-977e-12dd5efa1bf1.png)

**Comment by tasomaniac** [comment]
For us the order will not match the website because of the Api we are
using.
But you are right. We can sort alphabetically at least.
I don't know. How should we address this.

**Comment by tasomaniac** [comment]
I've found this unofficial API but it is also in different order. 
But it can fix issue #370 because it has `deleted: true` parameter of ex GDEs

**Comment by tasomaniac** [comment]
We have issue #370 for migrating to the official GDE API. That is also not perfect. But anyways, I will close this.
