### ISSUE TITLE
Ex GDE profiles are still displayed

### ISSUE THREAD

**Issue by PareshMayani** [gdg-x/frisbee#370]
As we know some of the GDEs have recently joined Google and so they should not be continue with GDE (as far as I know) and so the website is not listing them in the directory but our app is listing their profiles.

![screenshot_2015-07-10-11-37-15](https://cloud.githubusercontent.com/assets/888080/8613093/65a07d8a-26f8-11e5-97d8-a387bd53c248.png)

Use https://github.com/GoogleDeveloperExperts/experts-app-backend/blob/master/services/web_endpoints.py to retrieve the GDEs

**Comment by tasomaniac** [comment]
Yep, this is a problem I've been thinking about recently. It is because of
the API. The API is an unofficial API from a Googler. I emailed him about
the bug and he didn't respond.

To solve this we would have to right or own api.

**Comment by mauimauer** [comment]
Please flag this up with the people maintaining gdg-x/hub or try to get a proper API from the guys over at GoogleDeveloperExperts/experts-app-web

**Comment by Splaktar** [comment]
I don't believe that anyone is maintaining gdg-x/hub at this time. We tried to find some people with Node.js and Mongo experience at the GDG summit, but no one stepped up. I plan to contribute some more, but Angular Material, boomerang, and Frisbee are keeping me pretty busy atm.

For now this issue is quite low priority and shouldn't be looked at until 2.2 and 2.3 milestone issues can be addressed.

**Comment by tasomaniac** [comment]
Is there a way to set priority in Github? Is it done with labels? Should we start prioritize the issues.

**Comment by Splaktar** [comment]
Yes, you would create labels like `priority: critical` `priority: high` `priority: low` etc. The Angular and Angular-Material team have a nice set of labels (some specific to web dev) for reference.

**Comment by tasomaniac** [comment]
We can use this official API. 
https://omega-keep-406.appspot.com/_ah/api/gdetracking/v1.0b2/account/account

GDE categories have recently changed. The API still shows old product categories. It will be updated soon. So we can wait a little bit before we migrate to the API above.

**Comment by tasomaniac** [comment]
It seems that the un-official API we are using is getting better. This problem is fixed by itself automatically. Closing now.
