### ISSUE TITLE
GDE profile pic mismatch

### ISSUE THREAD

**Issue by PareshMayani** [gdg-x/frisbee#371]
One more issue about GDE and this time it is about profile pic mismatch on web and mobile app.

Based on the profile pic, I think android app is referring the Google+ profile pic and web directory is referring the pic given by the person!

Check the profile of our own @tasomaniac in attached web directory and app snaps.

![profile pic mismatch](https://cloud.githubusercontent.com/assets/888080/8613155/37d373b6-26f9-11e5-9baa-ef74acc06ad5.PNG)

![screenshot_2015-07-10-11-42-19](https://cloud.githubusercontent.com/assets/888080/8613157/3a426b5c-26f9-11e5-9afe-c516c2b6f563.png)

**Comment by tasomaniac** [comment]
GDE web page updates itself only twice a month. It also gets the pictures
from Google+. We didn't give any.
I am sure that it will update and match.

**Comment by tasomaniac** [comment]
We use a really old, unofficial, abandoned API build by only 1 person within Google. So it is really hard for us to implement this. Besides, it shows the most updated Google+ picture of the developer. I will go ahead and close this.

**Comment by tasomaniac** [comment]
GDE website is updated and they fixed it.

**Comment by PareshMayani** [comment]
@tasomaniac :+1:
