### ISSUE TITLE
G+ Community into Leads section

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#372]
As described here, 
https://plus.google.com/u/0/+MichaelPrentice/posts/SDHMf6BkYGh
we should add G+ community link into Leads section.

**Comment by Splaktar** [comment]
:+1: Here are some other resource links (perhaps linking to this GitHub wiki would be good as well): https://github.com/GDGNorthAmerica/info-and-resources/wiki/Resources

**Comment by friedger** [comment]
the other resources should go in the GDG wisdom, I'd say. Otherwise we have to redo the same work as the GDG wisdom project.

**Comment by friedger** [comment]
See https://github.com/gdg-wisdom/wisdom-2015/commit/0cb6e95498f6f61942c5b6a907819cef2f69387a

**Comment by friedger** [comment]
fixed by #387
