### ISSUE TITLE
Should validate empty input

### ISSUE THREAD

**Issue by PareshMayani** [gdg-x/frisbee#374]
Issue is in Feedback dialog. If user clicks on a send button then it should validate inputs, before actually making a call.

**Comment by tasomaniac** [comment]
Are we talking about just the email address validation? Or do we have
anything else?

**Comment by jmsalcido** [comment]
as we are using Doorbell.io for the feedback I think we only should validate the email address, we already have a Utils.java that contains a isEmailAddress method that we could use before doing the call.

**Comment by PareshMayani** [comment]
I am talking about empty input. We are making a call even though user leaves fields empty and click on send button. There should a proper message saying that "Please input message" or "Please input email address"!

**Comment by PareshMayani** [comment]
@tasomaniac thanks, will fix it up!

**Comment by friedger** [comment]
@PareshMayani What needs to be done for this one?

**Comment by tasomaniac** [comment]
This is already fixed in the above referenced prs
