### ISSUE TITLE
Implement Nearby API for Arrow Game

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#377]
Here is the reference blog post: http://googledevelopers.blogspot.com.tr/2015/07/connect-with-world-around-you-through.html?linkId=15518057

It is not out yet but it would be really fun to ditch NFC and QR codes for this.

**Comment by stefanhoth** [comment]
:100:

**Comment by friedger** [comment]
Someone should reach out to devrel and ask for early access.

Also for check-in with the organizer at the event. This would solve the
problem of list of attendees..
Am 14.07.2015 23:09 schrieb "Stefan Hoth" <notifications@github.com>:

**Comment by tasomaniac** [comment]
I just asked. Good idea.

**Comment by tasomaniac** [comment]
I've asked couple of Googlers and we talked it in GDE community. They are currently not doing early access because it will be released really soon.

**Comment by friedger** [comment]
Here I tried to do a checkin on-site. https://github.com/gdg-x/frisbee/tree/feature/nearby

**Comment by tasomaniac** [comment]
Code looks good. How does it work?
I was thinking for the Arrow game. For 2 people to meet. What you've done
is for event check-ins right?

**Comment by tasomaniac** [comment]
Closing this because the Arrow game is now removed from the app.
