### ISSUE TITLE
Add EditorConfig support to project to make onboarding new contributors easier

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/frisbee#378]
As mentioned in #376, we need to add an `.editorconfig` file to the repo so that new contributors will automatically have their formatting setup correctly.

Find out more here: http://editorconfig.org/

**Comment by tasomaniac** [comment]
I couldn't find any website for native Android Studio editorconfig integration. All the methods include Android Studio Plugin installation. Which I think we cannot do.

There won't be any harm to add a config file though.

**Comment by Splaktar** [comment]
It's built into Android Studio. Settings->Editor->Code Style then Check "Enable EditorConfig".

**Comment by tasomaniac** [comment]
Oh nice. I didn't know that. Let's do this.

**Comment by friedger** [comment]
fixed by #524
