### ISSUE TITLE
News: Can't scroll up, always tries to refresh

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/frisbee#399]
Running the latest debug build from develop, once I scroll down on the News screen, I can't scroll back up. It always tries to refresh the view instead of scrolling up.

**Comment by tasomaniac** [comment]
The last change that I made to fix memory leak may caused that problem. It
runs on my machine well. What do you use? Lollipop or below?

**Comment by Splaktar** [comment]
Running the latest Android M on Nexus 9.

**Comment by Splaktar** [comment]
Same behavior on Nexus 6 with Lollipop.

**Comment by Splaktar** [comment]
You can scroll up while it is refreshing, so it doesn't block all ability to scroll up. But it should only refresh when you can't scroll up any farther and pull down. Not just any time you pull down.

**Comment by tasomaniac** [comment]
Yeah I now. The canScrollUp function in RecyclerView should have done it. I
will check what is wrong.
