### ISSUE TITLE
Events: Upcoming events should be first, past events after

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/frisbee#400]
There should possibly be 2 sections to the events screen. One for future events and one for past events.

Currently I'm seeing the oldest event (from 2 months ago) first, which is the least interesting event to me. Then I have to scroll down below the fold to see my chapter's next event (which is the one I care the most about).

**Comment by PareshMayani** [comment]
It's already in our issues list :) #311

**Comment by Splaktar** [comment]
OK, I guess my search was just about the sorting so I didn't see that issue, but it should also fix this issue.

**Comment by PareshMayani** [comment]
Yes that issue is about displaying 2 sections only, upcoming events section on top and past events section below to that!
