### ISSUE TITLE
GoogleApiClient callbacks are not unregistered

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#413]
unregisterConnectionCallback and unregisterFailedConnectionCallback should be called in GgdActivity and GdgNavDrawerActivity.

https://developers.google.com/android/reference/com/google/android/gms/common/api/GoogleApiClient#unregisterConnectionCallbacks(com.google.android.gms.common.api.GoogleApiClient.ConnectionCallbacks)

**Comment by friedger** [comment]
Related discussion on https://github.com/gdg-x/frisbee/pull/407

**Comment by friedger** [comment]
@tasomaniac  Fixed by https://github.com/gdg-x/frisbee/pull/468?

**Comment by tasomaniac** [comment]
Yes :+1: forgot to tag it.
