### ISSUE TITLE
TabLayout issue: Two lines title for "For leads" tab

### ISSUE THREAD

**Issue by PareshMayani** [gdg-x/frisbee#414]
"For leads" tab is getting displayed in two lines, observed in Moto G phone. 

![screenshot_2015-07-26-16-23-44](https://cloud.githubusercontent.com/assets/888080/8893571/eed953d0-33b2-11e5-9707-a05ed6c7e648.png)

**Comment by friedger** [comment]
Same for Third party libraries in About activity

**Comment by tasomaniac** [comment]
Interesting. 3rd party libraries section is displayed normally on my phone.
Because it uses scrolling tabs.

Sorry for bringing in another issue when I integrated tablayout. It was
necessary. What should be done? Should we detect and convert it to
scrolling tabs?

**Comment by PareshMayani** [comment]
Thanks @tasomaniac, will look into it over the weekend.

**Comment by PareshMayani** [comment]
Solution could be either we define a custom textview or make tabs scrollable!

Check about taking a custom textview and inflating it but again here is an issue, it would be ellipsized at end if we make it a single line textview. http://stackoverflow.com/questions/31698756/remove-line-break-in-tablayout

**Comment by tasomaniac** [comment]
We can make the tabs scrollable only on the small phones.

**Comment by tasomaniac** [comment]
The latest support library is much more clever for these. If there is not enough space, it just makes the text smaller. I think it is fine for us for now. Closing this for now.
