### ISSUE TITLE
Setup continous distribution

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#417]
local.properties and the p12 file is uploaded to travis.
It should be possible to publish apks by add the gradle task
```
publishApkRelease
```

**Comment by Splaktar** [comment]
The changes to add these encrypted files seems to have broken the Travis build. Please revert or fix ASAP. All PR builds are failing atm.

**Comment by friedger** [comment]
I am sorry for the broken build. Should be fixed now.

**Comment by tasomaniac** [comment]
The new Travis infrastructure is not working for us right? I tried to do that as well. The new infrastructure is faster but has less memory I think. 

I couldn't enable it with my pomodoro project as well where I have 3 modules to build including wear app.
