### ISSUE TITLE
Implement the new FCM registration

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#442]
It can be related to this. 
https://plus.google.com/+AndroidDevelopers/posts/TqPcucE9zL9

We should check if it is the same case in 2.1 production version. 

Do we even have access to push notification server of ours? Is it the hub webpage?

**Comment by Splaktar** [comment]
It looks like we've got about half of the migration done (receiver) but still need to update the other half (service).

The problem seems to be related to this:

    public class GcmIntentService extends IntentService

From https://developers.google.com/cloud-messaging/android/client

    replace the current service declaration that extends IntentService to the new GcmListenerService
    Refactor the current IntentService service implementation to use GcmListenerService

More details:

    A declaration of GcmListenerService, which enables various aspects of handling messages such as detecting different downstream message types, determining upstream send status, and automatically displaying simple notifications on the app’s behalf.
    A service that extends InstanceIDListenerService, to handle the creation, rotation, and updating of registration tokens.

**Comment by tasomaniac** [comment]
This is the class where we receive the push messages. I am not 100% sure but it is not the place where the registration occurs.

**Comment by Splaktar** [comment]
Right, it's not related to registration here. I'll take a look at that real quick.

Are we even using GCM for anything useful in the app? I'm seeing 10-20 registrations per day, but 0 messages per day.

**Comment by tasomaniac** [comment]
We are supposed to send event notifications to the users but it is not
working for a looong time.

**Comment by Splaktar** [comment]
We need to do something like this on registration:

    InstanceID instanceID = InstanceID.getInstance(FirstStartActivity.this);
                        String token = instanceID.getToken(BuildConfig.GCM_SENDER_ID,
                                GoogleCloudMessaging.INSTANCE_ID_SCOPE, null);

Then do the send to GdgXHub server in the service's listener. Details here: https://developers.google.com/cloud-messaging/android/client#sample-register

Examples here:
https://github.com/googlesamples/google-services/blob/master/android/gcm/app/src/main/java/gcm/play/android/samples/com/gcmquickstart/MyInstanceIDListenerService.java
https://github.com/googlesamples/google-services/blob/master/android/gcm/app/src/main/java/gcm/play/android/samples/com/gcmquickstart/RegistrationIntentService.java
https://github.com/googlesamples/google-services/blob/master/android/gcm/app/src/main/java/gcm/play/android/samples/com/gcmquickstart/MyGcmListenerService.java

**Comment by Splaktar** [comment]
We might just want to disable GCM in the app for 2.2 and then look at reimplementing it in 2.3 or 3.0. There are a lot of changes needed here and the net result will be nothing that the user can see in 2.2. Perhaps we can just make the checkbox disabled and unchecked in 2.2 and disable it in settings as well.

**Comment by tasomaniac** [comment]
Or we can leave the UI as is and comment out the network operation and tell the user it is successful. It doesn't do anything anyways. 
And reimplement it in 2.3 as you say. It will be so much easier.

**Comment by Splaktar** [comment]
Registration disabled in #444 to fix login blocking bug. This issue is to re-implement GCM with the new APIs mentioned above.

**Comment by friedger** [comment]
See https://firebase.google.com/docs/cloud-messaging/ for details

**Comment by friedger** [comment]
Started in https://github.com/gdg-x/frisbee/tree/feature/442_cloudmessaging

**Comment by friedger** [comment]
Should be working. Not sure about google-service.json and what we do with the backend/hub

**Comment by tasomaniac** [comment]
This was about registration and push notifications related to events. 
Let's split this into 2 because the first part (registration) is now done in #644 

I don't know how to send event notifications from Firebase because we don't have the data there yet. 
Once we have the data, we can create `topic`s for every chapter. Users will register those `topic`s. And once there is a new event in a chapter, we will create a notification to be sent to that `topic` in FCM.

**Comment by tasomaniac** [comment]
Fixed by #644
