### ISSUE TITLE
Pulse numbering bug. 

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#451]
As it can be seen in the screenshots, we have a problem with the numbering of the items. 

![screenshot_20150802-234650](https://cloud.githubusercontent.com/assets/763339/9027966/8fb94422-3971-11e5-9e95-a506602b553a.png)
![screenshot_20150802-234709](https://cloud.githubusercontent.com/assets/763339/9027967/8fbdee28-3971-11e5-82cd-ec8c5eb34b81.png)

**Comment by Splaktar** [comment]
First one seems OK. Second does not.

**Comment by tasomaniac** [comment]
First one has two 4s and two 9s :smile:

**Comment by Splaktar** [comment]
Yes and that is correct since they are ties. 6 and 6. 0 and 0.

**Comment by PareshMayani** [comment]
+1 @Splaktar that's correct Said as there is tie.

**Comment by tasomaniac** [comment]
Oh I didn't know that. Thank you guys. 
I cannot reproduce the bug in Australia either. I have 1, 2, 3 now as the numbers. 
And I realized that we have 2 Australia in the Country list :)

**Comment by tasomaniac** [comment]
I opened this issue but cannot reproduce this.

**Comment by tasomaniac** [comment]
I actually reproduced this again while I am testing the app. Idk how to do it though.

**Comment by tasomaniac** [comment]
Here is one. I don't how how I did it. It seems that it happens when you change the country. 

![image](https://cloud.githubusercontent.com/assets/763339/9659161/504be566-5257-11e5-925b-dece7f926d3f.png)
