### ISSUE TITLE
Refactor welcome 1st step Fragment

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#464]
We have 6 different copied and pasted version of `fragment_welcome_step1.xml`. It should be at most 2. 
Most of them are exactly the same. Those can be deleted and instead made a ref.

**Comment by PareshMayani** [comment]
I have just done re-factoring of welcome step 1 layouts. As said said, I have deleted other layouts as it wasn't needed and we haven't taken different layouts for any of the screens like welcome step two or three.

**Comment by PareshMayani** [comment]
Landscape layout: Given center horizontal to the "Welcome. Choose your home GDG" layout

![device-2015-10-02-193500](https://cloud.githubusercontent.com/assets/888080/10248450/3693f422-693d-11e5-9cef-031e16c55b08.png)

**Comment by PareshMayani** [comment]
Nexus 6 Portrait and landscape layouts

![device-2015-10-02-194159](https://cloud.githubusercontent.com/assets/888080/10248530/bfbd95c8-693d-11e5-8318-e25f588f1cfd.png)
![device-2015-10-02-194105](https://cloud.githubusercontent.com/assets/888080/10248531/c3c55a20-693d-11e5-86af-bb8caa870fab.png)

**Comment by tasomaniac** [comment]
Nice :+1: Where is the PR? :smile_cat:

**Comment by PareshMayani** [comment]
@tasomaniac dude can't beat your speed :D

**Comment by PareshMayani** [comment]
@tasomaniac I guess this should be closed as it has already been fixed!

**Comment by tasomaniac** [comment]
Sure
