### ISSUE TITLE
Replace AnimationImageView with normal ProgressBar

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#466]
We don't need `AnimationImageView`. It can be replaced with normal `ProgressBar` with custom `indeterminateDrawable` attribute. 

In fact I already started working on this.

**Comment by PareshMayani** [comment]
:+1:

**Comment by friedger** [comment]
@tasomaniac Could you show where you started?

**Comment by tasomaniac** [comment]
I've started this but it is really a big issue. Currently all of my is local. Do you want me to push it?

**Comment by PareshMayani** [comment]
Could you please share the progress? 

Because I think it can be easily done with a single vector asset and animating the same, so at the end we will require a single vector asset to make it same as current animated image view.

**Comment by tasomaniac** [comment]
I will finish this as soon as possible. I find couple of design problems
whole doing it.

**Comment by PareshMayani** [comment]
:+1:

**Comment by friedger** [comment]
Is this still in progress? @tasomaniac

**Comment by tasomaniac** [comment]
Finally pushed the work I've done on this. 
Please review @PareshMayani and @friedger
