### ISSUE TITLE
Create Play Store Developer Page

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#467]
This year at Google I/O they introduced developer pages where you have a special page for the developer account. We need 
- Promotional Text
- Developer Icon 512x512
- Header Image 4096x2304

**Comment by friedger** [comment]
Developer Icon: https://avatars3.githubusercontent.com/u/4521984?v=3&s=512

**Comment by friedger** [comment]
Header Image something like https://plus.google.com/events/gallery/cf489kbj996us9q1fsofo9k3t4g?pid=6178107869745348018&oid=114323788136121580292&sort=6

**Comment by friedger** [comment]
Page has been created: https://play.google.com/store/apps/dev?id=8811626365943632944
