### ISSUE TITLE
Replace zxing with new vision Api

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#474]
We can replace zxing implementation with the new vision Api. 
We also generate barcodes offline. I don't think vision api has that feature. But we should look into it.

**Comment by friedger** [comment]
What I heard, the implementation is not very reliable.

**Comment by tasomaniac** [comment]
We are using Zxing to generate QR Codes. Vision API is just for reading barcodes. So it cannot replace it at all. Closing this.

**Comment by friedger** [comment]
And we don't want to use it for barcode reading due to https://github.com/googlesamples/android-vision/issues/98
