### ISSUE TITLE
Use Chrome Custom Tabs for external links. 

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#480]
If Google+ is installed it is not logical to use Chrome Custom Tabs. 
But for all other things, it would be a great improvement to use Chrome Custom Tabs. 

More info: 
http://android-developers.blogspot.com.tr/2015/09/chrome-custom-tabs-smooth-transition.html
https://developer.chrome.com/multidevice/android/customtabs

**Comment by friedger** [comment]
@tasomaniac Android will figure out how to use the tab information, hopefully... probably we don't want the warm up for now.

**Comment by tasomaniac** [comment]
I don't think custom tabs forward links to external apps. The benefit of custom tabs is that user never leaves your app. So most probably custom tabs won't redirect links to external intents.

**Comment by tasomaniac** [comment]
But it will be perfect for help section. I too don't think warm up makes sense for us
