### ISSUE TITLE
Removing plus api dependency

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#483]
Google Plus Api dependency is not specifically designed for Android and it comes with lots of dependencies. Most important thing is it depends on Apache Http Client. 

It is used in 2 places: NewsFragment where we get Google+ feed and while we are getting profile pictures of people. Both of them can be replaced with REST calls using Retrofit. 

What do you all think?

```
    useLibrary 'org.apache.http.legacy'
    compile 'com.google.http-client:google-http-client-gson:1.20.0'
    compile 'com.google.apis:google-api-services-plus:v1-rev126-1.18.0-rc'
```

**Comment by friedger** [comment]
We should use this: https://developers.google.com/+/mobile/android/ ??

**Comment by tasomaniac** [comment]
I already tried doing it. It is already in our dependency list. I wish we could use it. That would be really clean. That api in Google Play Services does not include related APIs to get news feed. It doesn't even support getting other people's public profile. It only has APIs related to signed in user.

**Comment by friedger** [comment]
Play service contains an api to load public profiles: https://developers.google.com/android/reference/com/google/android/gms/plus/People.html#load%28com.google.android.gms.common.api.GoogleApiClient,%20java.lang.String...%29

**Comment by friedger** [comment]
This issue is solved by creating a rest service using retrofit.

**Comment by tasomaniac** [comment]
Plus Api brings us huge plus dependency. It includes apache http client, we
have to use. OkHttp urlconnection dependency etc.

Not easy but we should do this.

**Comment by friedger** [comment]
There is a limit of 10.000 requests per day. Just for future planning..

**Comment by tasomaniac** [comment]
Not to be confused. We have 2 Plus APIs in our code. This one was about removing the Google Plus client API which is a Java modue. 
There is also Plus api coming from Google Play Services.
