### ISSUE TITLE
App Invites integration

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#488]
More information can be found here:

https://developers.google.com/app-invites/android/guides/app

In the app visit the about section and use the share action.

![device-2015-11-24-090428](https://cloud.githubusercontent.com/assets/1449049/11361068/9d752a1e-928a-11e5-8c41-b9e834874338.png)

**Comment by friedger** [comment]
@tasomaniac What is the status here? Is there a branch?

**Comment by tasomaniac** [comment]
As far as I remember I did some work in the about page and you merged it.
It is merged but we didn't test it at all.

**Comment by friedger** [comment]
fixed by #489
