### ISSUE TITLE
Chapters sorting when location is not available

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#491]
When user's location is not available, the app does the same sorting with location of 0.0, 0.0 coordinates. 
Instead, don't take the location into account when it is not available. Just sort alphabetically.

**Comment by friedger** [comment]
In https://github.com/gdg-x/frisbee/blob/develop/app/src/main/java/org/gdg/frisbee/android/chapter/ChapterComparator.java#L41 there is a check for null location. Where does the 0,0 come from?

**Comment by tasomaniac** [comment]
I am not sure. I will work on this today. 
What I am seeing in emulator that couple of chapters near equator shown at the top.
