### ISSUE TITLE
Implement App Links

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#492]
Implement App Links. 

Only thing to do in the Android side is to add autoVerify to IntentFilter 's. 
A json with the fingerprint of the app should be added to firefly. 

More here: https://www.youtube.com/watch?v=LQoohRwojmw
https://developer.android.com/intl/zh-cn/training/app-links/index.html

**Comment by friedger** [comment]
We should also support the applink.org protocol http://applinks.org/documentation/

**Comment by tasomaniac** [comment]
Should we? When they first released, it didn't sound really well. And being facebook behind it, I don't trust the protocol. 
Are you using it or have you tried it? Can you tell why we should implement it?

**Comment by friedger** [comment]
Having a better user experience is worth a trial. It does not harm and I like the open aspect. I haven't tried it. We could also try http://branch.io

**Comment by tasomaniac** [comment]
As we are only on Android, Google's App Indexing should be sufficient for us. App Indexing is better user experience. But do we need additional libraries?

**Comment by friedger** [comment]
App Indexing is not for deep linking.

**Comment by tasomaniac** [comment]
They are not 100% the same but when you implement App Indexing, you almost have to implement Android's deep linking. 
https://developer.android.com/training/app-indexing/deep-linking.html

**Comment by friedger** [comment]
I meant the other side, when launching a link from frisbee. The applink.org protocol comes after Google verified resolution (as this is built into the Android system). Requesting the applink meta data and resolving it will always return the verified app.

In addition to the json, we could add the meta data to firefly.

**Comment by tasomaniac** [comment]
Then, I don't understand what applinks.org is doing. :)
Will investigate it more.

**Comment by friedger** [comment]
Actually, I disagree that we should implement it. It would discourage other developers to create apps that would make use of our site. I am more for an open app ecosystem.

**Comment by tasomaniac** [comment]
I see your point now. You are right. This is not a must.
