### ISSUE TITLE
Implement VectorDrawable

### ISSUE THREAD

**Issue by PareshMayani** [gdg-x/frisbee#493]
It's time to convert all the possible PNG icons and drawables into the vector files and start using it.

VectorDrawable is available in Android studio 1.4. For more https://www.youtube.com/watch?v=8e3I-PYJNHg

**Comment by PareshMayani** [comment]
Let me if all you are agree to go ahead with the implementation, meanwhile I will prepare a demo to show you improvements and benefits of using it :)

**Comment by tasomaniac** [comment]
Go ahead and do it. It will improve the codebase quality a lot. 
You can easily replace the material icons that we are using.

**Comment by PareshMayani** [comment]
@tasomaniac thanks :) will start implementing and sending PR :)

**Comment by tasomaniac** [comment]
I am suggesting that we should close this. We can use vectors for new assets but I don't see any benefit of changing the old (working-fine) assets to vectors just because we can.
