### ISSUE TITLE
Update Play Store listing with screenshots from 2.2.2 release

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/frisbee#497]
When was the last time we updated these screenshots?

There are no 7 inch tablet screenshots.
10 inch tablet only has 3 screenshots.

An updated video and icon would also be something that we should think about :)

**Comment by Splaktar** [comment]
Here are a few that might be useful.

![achievements](https://cloud.githubusercontent.com/assets/3506071/11433940/f3490064-94ab-11e5-9a24-8d28b9551169.png)
![chapterevents](https://cloud.githubusercontent.com/assets/3506071/11433941/f34b134a-94ab-11e5-9440-2c29c082f3b3.png)
![devfest](https://cloud.githubusercontent.com/assets/3506071/11433942/f34d0c36-94ab-11e5-9bec-220f57528906.png)
![gde](https://cloud.githubusercontent.com/assets/3506071/11433939/f3486ed8-94ab-11e5-9e78-3ede5001eafa.png)
![leadssection](https://cloud.githubusercontent.com/assets/3506071/11433944/f358f014-94ab-11e5-96ea-e9d6af652f80.png)
![pulse](https://cloud.githubusercontent.com/assets/3506071/11433943/f3586054-94ab-11e5-8a6e-e86f16fbc1d2.png)
![pulseattendees](https://cloud.githubusercontent.com/assets/3506071/11433946/f3632552-94ab-11e5-9868-81e60ccf0d4a.png)
![sidenav](https://cloud.githubusercontent.com/assets/3506071/11433945/f362e704-94ab-11e5-94d7-9a4e4ac0be8c.png)

**Comment by tasomaniac** [comment]
Did you already update them, or should we update them with these?

Video would be awesome. I did some effort to find the original file for the video but no luck. Making that video from scratch would be too hard.

**Comment by Splaktar** [comment]
I didn't have time to update them. These should help for the phone, but they don't cover the 7 or 10 inch tablet shots.

**Comment by friedger** [comment]
@tasomaniac as agreed in Januar hangout

**Comment by Splaktar** [comment]
Hooray!
