### ISSUE TITLE
Upgrade from Cloud Save API to Games Snapshot API

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#499]
http://android-developers.blogspot.be/2014/11/keeping-your-saved-games-in-cloud.html

**Comment by tasomaniac** [comment]
Migrating info here: https://developers.google.com/games/services/android/savedgames?hl=en#migrating_from_the_appstate_api

**Comment by tasomaniac** [comment]
Here is the discussion @ianhanniballake and I made about this yesterday. 

https://github.com/ianhanniballake/TripleSolitaire/commit/d747ff06df85b5cc9f27d805eaf2bc0dab473d96#commitcomment-14714517

**Comment by Splaktar** [comment]
Yes, I agree that 10 months was too little time for the removal of this API.

**Comment by tasomaniac** [comment]
Google usually just deprecates and does not remove APIs for years. This was unexpected from my side.

**Comment by Splaktar** [comment]
Yeah, I'm looking at replacing the use of `AndroidHttpClient` in one of my apps. It was deprecated for a long time, but I never had time to remove it. Now I have to... I've also had them break a number of other Play Services APIs that I've used. It's nice to get their support with those services, but you kind of have to expect them to be alpha and breaking changes coming every 6-12 months. 

This is not a good development experience when you aren't employed full time to update the app.

**Comment by tasomaniac** [comment]
`HttpClient` is actually not removed. It is hidden. You can re-enable it via a gradle method and it will work just like before.

**Comment by Splaktar** [comment]
Yes, but AFAIK okhttp is better in every way. I was able to replace the code pretty easily and saved about 20 lines of code and a lot of complexity for each instance.

**Comment by friedger** [comment]
This is a bug, as the App state seems read-only

**Comment by tasomaniac** [comment]
Do you mean a bug from Google?
It is read only. The data will be always there but if we upgrade GMS
library, we won't have the Api to access the data.

**Comment by friedger** [comment]
It is a bug in our app because you can tag the same organizer more than
once and the number of tagged organizers does not increase neither.

**Comment by tasomaniac** [comment]
Yes that's right. We have to migrate the API as soon as possible to have
write support. Basically arrow tagging game is not working anymore.
