### ISSUE TITLE
Replace deprecated methods like People.getCurrentPerson() with GoogleSignInAccount

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#519]
New Google login API in GMS 8.3+ solves this actually. But still if we use Google Play Games, it would require Google+ anyways. There is no Play Games without Google+ yet. 

So if the user do not have Google+, we can disable Game APIs.

**Comment by friedger** [comment]
Also replace `Plus.AccountApi` and `GoogleAuthUtil.getToken`

**Comment by friedger** [comment]
related to #579

**Comment by tasomaniac** [comment]
Blocked by #616

**Comment by tasomaniac** [comment]
Fixed by #690
