### ISSUE TITLE
Move login/logout to nav drawer

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#526]
The current UI with a checkbox does not follow the branding guidelines

* for G+
https://developers.google.com/+/branding-guidelines
* for Google Sign-In
https://developers.google.com/identity/sign-in/android/sign-in#add_the_google_sign-in_button_to_your_app

**Comment by tasomaniac** [comment]
Also the button in the onboarding uses a really old G+ icon. We have that icon inside our app. 
Instead, we can remove the PNGs completely and use the button custom view from Play Services.

**Comment by esoxjem** [comment]
I can try to fix this as my first issue. Do we have icons for login/logout nav items?

**Comment by friedger** [comment]
There is the Google button

Have a look at branch 621_signin (or so)

**Comment by tasomaniac** [comment]
I believe we should make it look like all the other Google material design apps. 
When the user is logged in we should have their name in the header. 
In logged out state, we can still have a text that says login. I'm not really sure what would be the best.

**Comment by esoxjem** [comment]
In that case, clicking on the header should open the account chooser. Logout can still be kept under Settings?

**Comment by tasomaniac** [comment]
Definitely. Logout should stay in settings. 
Also we don't have multiple account support. Don't work too much on account chooser UI.

**Comment by esoxjem** [comment]
This is what I have so far:

<img src="https://cloud.githubusercontent.com/assets/7837006/19142852/0f5b608a-8bbe-11e6-9a6f-3ae03620530f.jpg" width="300">
<img src="https://cloud.githubusercontent.com/assets/7837006/19142851/0f41839a-8bbe-11e6-9419-6a6e768a98ff.jpg" width="300">

Also, does anything need to change on the settings activity?

**Comment by tasomaniac** [comment]
Looks great. 👍 
I think we can leave the things in Settings as they are. That would be a separate issue to tackle. 

For the upcoming PR, please try to hook up with the current login mechanism we have in `GdgActivity`. Please do not refactor unrelated things to avoid conflict. It's because I'm working on migrating to the new auth apis. Most of the Google login related stuff will be removed anyways.

**Comment by friedger** [comment]
You are supposed to use the Google branded login button..

Le 6 oct. 2016 09:14, "Said Tahsin Dane" <notifications@github.com> a
écrit :

**Comment by tasomaniac** [comment]
Do we really have to?
I don't know any single app example putting branded button into the nav drawer. Even Google Apps has account chooser where you can add new accounts. And it just has a plus icon.

**Comment by friedger** [comment]
Google apps use the account manager.

https://developers.google.com/identity/branding-guidelines

Le 6 oct. 2016 10:30, "Said Tahsin Dane" <notifications@github.com> a
écrit :

**Comment by tasomaniac** [comment]
As far as I understand this guidelines is for screens where you have different sign in providers like Facebook etc. 
I don't think any single app has Google logo in their nav drawer. I don't think Google forces us to put their logo in our drawer. It would look very bad. 

This Google button will be in `FirstStartActivity` anyways. If we really want to have it everywhere, we can create another LoginActivity. Clicking the `Login/Register` text in the nav drawer can open that Activity, and then we can have this button with a little explanation.

**Comment by esoxjem** [comment]
For now, we could just start the login flow on click of `Login/Register` and if required add a separate login screen with the Google custom button later.
