### ISSUE TITLE
Attendees of an event should easy open the event details page

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#531]

**Comment by friedger** [comment]
With deeplinking this is sufficient

**Comment by tasomaniac** [comment]
Event organizer should provide the event shortlink somehow somewhere. I can be a URI Beacon, QR Code etc. 

And additionally we can also send push notification to users once their home chapter's events are starting.

**Comment by friedger** [comment]
See https://github.com/gdg-x/frisbee/wiki/FAQ-for-organizers

**Comment by tasomaniac** [comment]
Very good! Do you plan to put that into Wisdom as well?

**Comment by friedger** [comment]
Even better
