### ISSUE TITLE
GDG Augsburg does not appear in the list of chapters

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#540]
It appears in the list at https://hub.gdgx.io/api/v1/chapters?perpage=999

However, does not show in the onboarding or the settings list.

**Comment by tasomaniac** [comment]
It is in my app when I search it.

**Comment by tasomaniac** [comment]
![screenshot_20160121-133045](https://cloud.githubusercontent.com/assets/763339/12479393/74bb387a-c043-11e5-9c04-ecc9177b430e.png)

**Comment by friedger** [comment]
So what? :-)
Maybe it is related to the distance?

![screenshot_2016-01-21-12-39-30 1](https://cloud.githubusercontent.com/assets/1449049/12479555/1c96c562-c03c-11e5-8348-d908a92da814.png)

**Comment by tasomaniac** [comment]
I was thinking that it may be related to the cache we have. But you already cleared data. It shouldn't be related to that. 
We don't do remove anything while we are doing distance calculation. 
Can you disable location and retry? 
And maybe see the debug logs tagged "OkHttp"

**Comment by friedger** [comment]
It looks like an issue with caching.
The server sometimes return 719 sometimes 730 chapters. Which and when, I don't know.

**Comment by Splaktar** [comment]
Might have been a hub issue. I adjusted some things last night. Can you please re-test this?
