### ISSUE TITLE
GoogleApiClient should be reconnected after sign-in state change. 

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#551]
I go into Settings and change sign-in state and nothing changes. It is because GoogleApiClient is already connected. 
We should recreate it and reconnect it upon state change. 

The problems I saw: 

- In settings, when sign-in is checked, sign-in process should immediately start. 
- After sign-in in Settings, when the user goes back to MainActivity, user's profile picture should be shown in nav drawer. "For Leads" section should be enabled. 
- In signed-out state, if user clicks arrow game, it should sign the user in and takes the user to Arrow after a successful sign-in.
- After sign-out, MainActivity GoogleApiClient should be reconnected and the Activity should go into signed-out state (user's profile picture should be removed)

**Comment by friedger** [comment]
I have started some coding in branch https://github.com/gdg-x/frisbee/tree/fix/551_signin
but I don't really know enough about `GoogleApiClient`. If you do: http://stackoverflow.com/questions/35085725/how-to-remove-api-and-scope-from-googleapiclient-in-android

**Comment by tasomaniac** [comment]
Closed by #560
