### ISSUE TITLE
Redesign the spinner on the MainActivity 

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#562]
Redesign it to make it easier to find chapters in the huge list.

Replace the Spinner with a Button with a right carret that looks like a Spinner. 
On click of the button, re-use the implementation found in Settings.

**Comment by tasomaniac** [comment]
@friedger I have an idea on this. I really like your implementation in Settings page with a Dialog. It looks really nice and it has search. 
What about removing the Spinner and replacing it with that Dialog? 
The look can stay same. We can have a spinner indicator on the right hand side. On click, it will open the Dialog. 
What do you think?

**Comment by friedger** [comment]
Sounds good to me.

**Comment by tasomaniac** [comment]
I've worked on this quite a lot. Since DialogPreference is really integrated into Preferences implementation itself, it was not really an easy job to do.
