### ISSUE TITLE
Should remove httpurlconnection depedency

### ISSUE THREAD

**Issue by iNoles** [gdg-x/frisbee#564]
"The Apache HTTP client and HttpURLConnection APIs are deprecated. They continue to work as they always have, but we're moving everything to the new OkHttp 3 API. The okhttp-apache and okhttp-urlconnection modules should be only be used to accelerate a transition to OkHttp's request/response API. These deprecated modules will be dropped in an upcoming OkHttp 3.x release."

https://github.com/square/okhttp/blob/master/CHANGELOG.md

**Comment by tasomaniac** [comment]
Thank you for the opening an issue for this. I've been thinking about it but I forgot to open an issue. 

I think this class [GapiOkHttpRequest](https://github.com/gdg-x/frisbee/blob/develop/app/src/main/java/org/gdg/frisbee/android/api/GapiOkHttpRequest.java) is the only one using it. It has to be rewritten.

**Comment by iNoles** [comment]
with GapiOkTransport, I am not too sure, I know Android's implementation of Httpurlconnection uses okhttp backend too.
