### ISSUE TITLE
Update Wisdom Gitbook link to to 2016 version

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/frisbee#567]
It should probably just use the http://wisdom.gdgroups.org link.
It currently uses http://gdg-wisdom.gitbooks.io which is the 2015 version.

**Comment by fuentespatrick** [comment]
May I ask the steps to reproduce in the app?

Also, I ran into a problem with the http://wisdom.gdgroups.org/ URL (see http://imgur.com/CxyGhXX)
Is that definitely the URL to use?

**Comment by Splaktar** [comment]
Strange, that link is working for me. Try it again?

In the app, open Home GDG and then open the For Leads tab and select GDG
Resources.

**Comment by tasomaniac** [comment]
@fuentespatrick your screenshot can be a temp problem with Gitbook. 

Both links works fine for me. The link in the app should be updated.

**Comment by fuentespatrick** [comment]
The link works great for me now.

**Comment by fuentespatrick** [comment]
I can take a crack at this and submit a PR.
Should I do anything else like remove unused constants?
(e.g. –
    public static final String GOOGLE_DEVELOPERS_YT_ID = "UC_x5XG1OV2P6uZZ5FSM9Ttw";
    public static final String ANDROID_DEVELOPERS_YT_ID = "UCVHFbqXqoYvEWM1Ddxl0QDg";
    public static final String YOUTUBE_DEVELOPERS_YT_ID = "UCtVd0c0tGXuTSbU5d8cSBUg";
    public static final String TRUSTSTORE_PW = "VU%&ibkr45pnq39v53x";
    public static final int ARROW_STATE_KEY = 1;
    public static final int ARROW_DONE_STATE_KEY = 2; )

**Comment by Splaktar** [comment]
You should keep your PR as small and tight as possible.

If you have a question about unused constants, then the place to go is https://gitter.im/gdg-x/frisbee

**Comment by tasomaniac** [comment]
If you can send a separate PR for the removal of unused resources that would be better. Thanks, bye

**Comment by tasomaniac** [comment]
Fixed by #568
