### ISSUE TITLE
Remove unused constants

### ISSUE THREAD

**Issue by fuentespatrick** [gdg-x/frisbee#569]
e.g. –
public static final String GOOGLE_DEVELOPERS_YT_ID = "UC_x5XG1OV2P6uZZ5FSM9Ttw";
public static final String ANDROID_DEVELOPERS_YT_ID = "UCVHFbqXqoYvEWM1Ddxl0QDg";
public static final String YOUTUBE_DEVELOPERS_YT_ID = "UCtVd0c0tGXuTSbU5d8cSBUg";
public static final String TRUSTSTORE_PW = "VU%&ibkr45pnq39v53x";
public static final int ARROW_STATE_KEY = 1;
public static final int ARROW_DONE_STATE_KEY = 2;

**Comment by friedger** [comment]
:+1:

**Comment by friedger** [comment]
closed by #580
