### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by srisurya95** [gdg-x/frisbee#570]
I'm trying to compile the app in a server and not android studio just by git clone and ./gradlew
I get the following error
FAILURE: Build failed with an exception.

* Where:
Build file '/android/frisbee/app/build.gradle' line: 11

* What went wrong:
A problem occurred evaluating project ':app'.
> /android/frisbee/local.properties (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by tasomaniac** [comment]
You just need to create that file. You can create it like 

```
touch /android/frisbee/local.properties
```

Even if it is empty, I think it will work. 
I will close it now. If it is not working please re-open the issue.

**Comment by srisurya95** [comment]
It's fixed,thanks

**Comment by tasomaniac** [comment]
Great to hear that. You can also ask questions here: 
https://gitter.im/gdg-x/frisbee
