### ISSUE TITLE
Add "GCP" as new event series. 

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#574]
Google is organizing GCPNEXT event and GDG chapters are organizing GCPNEXT Extended event.

In Version 2.4 we should include that into our events section.

**Comment by fuentespatrick** [comment]
I'm new to the codebase. What kind of work would be involved?
E.G. – In the ListOfStuffActivity, there is an instance of the StuffAdapter, and they're related by the StuffAdapterListener interface. We'll need to add another listener method to the interface to create another category in the StuffRecyclerview using this URL: https://zombo.com/GCPNEXT

**Comment by tasomaniac** [comment]
No, in the application class all the TaggedEventSeries objects are initialized, you just have to add another one. And it's related Theme should be added as well. 

The colors needed can be taken from gcpnext.gdgroups.org

And an icon for left drawer should be created.
