### ISSUE TITLE
Question about Google SignIn vs Play Games

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#579]
I've looked into the new Sign In API from Google. It is a new dependency in GMS called auth. 

It really really simplifies the code. And it also simplifies the login process for the users. 
More info: 
https://developers.google.com/identity/sign-in/android/sign-in

The downside is that it cannot be used with Play Games at the same time. 

Here is what I am suggesting. To make the initial experience simpler/smoother, we won't ask for games related things upfront in the FirstStartActivity. It will just be a Google+ login. 
Then if the user opens Achievements or Arrow, we will start Games login. 

The problem with this is that user will not see achievements until they opt-in for Games by pressing Achievements or Arrow. 

The advantage is that, the code will be simpler, initial experience will be much better, and we can easily have auto-signin. With auto sign in, if the user is recently signed in in another device, Google will give us necessary info and we will skip the page 2.

**Comment by fuentespatrick** [comment]
@tasomaniac I like your suggestion.
My experience is only anecdotal, but I felt there was too much friction when I started using the app.

When I first heard about it, I stopped at that point, actually.
I only continued through after the GDG North America Summit because I wanted to contribute to the app.

Also, simpler code is *definitely* better if the code is going to be supported by a community instead of just a core team.

**Comment by friedger** [comment]
Splitting the login between gamers and non-games is indeed needed (as also commented by Ann-Kathrin B.)

We could then restrict achiements to the arrow game and after a certain level of user activities (number of opening or events visited) show a on boarding screen for Arrow.

Not sure how the code will be simpler if we have to handle two logins but yes, let's do it.

**Comment by friedger** [comment]
How do we check whether the user is an organizer?

**Comment by tasomaniac** [comment]
The code will I think be simpler because we will get rid of all the boilerplate code in GDGActivity. The new `auth` dependency is really really simple to use. I already did it locally. But then I realized that it forced me to remove Games.

@friedger When we know users Google+ ID, we just send it to Hub API and it tells us whether they are organizer or not.

**Comment by tasomaniac** [comment]
Feedback from the contributors outside of the core team is really valuable. Thank you @fuentespatrick

**Comment by friedger** [comment]
@tasomaniac How do we get the G+ ID? (! = Google sign in ID?)

**Comment by tasomaniac** [comment]
I was not thinking to remove Google+ login. We should somehow include Google+ login. 

When I think about it, 3 options I have in my mind: 

- Use Google+ without Games integration
- Ask the user if they are organizer before login and ask Google+ according to that. 
- Have Google login and Google+ login button at the same time.

**Comment by friedger** [comment]
I am in favour for G+ without Games integration so we can make use of the G+ button in the news fragment. For the records, organizers without G+ profile do not exist.

**Comment by tasomaniac** [comment]
If we do it without G+, that will only be useful for non-organizer attendees. 
I think what you are suggesting would be nice. It will be much harder if we try to separate G+ and Google sign in

**Comment by friedger** [comment]
Let's implement this in #526.

We could remove the login from the onboarding all together.
