### ISSUE TITLE
Plus API crash on EventOverviewFragment

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#583]
EventOverviewFragment first tries to get info about the Chapter by using Plus API. 

Plus API is now available only when the user is login. I don't know what we've changed here. I don't know if it was crashing before or not. 

But it is crashing now if we are not logged in. Every event page is crashing for me. When I login, they work fine. 

http://crashes.to/s/39f2ade756d

**Comment by friedger** [comment]
Retrieve the chapter profile image as described e.g. here http://stackoverflow.com/a/22532031/243599

**Comment by PareshMayani** [comment]
I just have got the same crash!

**Comment by friedger** [comment]
Fixed by #587
