### ISSUE TITLE
Crash when signing out

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#586]
When signing out in settings:
http://crashes.to/s/0faa6a480a5

The settings activity was opened from the events page

**Comment by tasomaniac** [comment]
It is opened from the event page. Why is the crash from MainActivity. It is
failing every time. Let me try.

**Comment by tasomaniac** [comment]
Yeah I reproduced it. Weird :(
I hope we won't have these crashes too often. We should stage rollout this.

**Comment by friedger** [comment]
When the server takes a while to return the organizer check and the user moved away from the main activity, the callback of the organizer check to the main activity crashes the app.
