### ISSUE TITLE
Changing chapter should not keep the scroll position in News page

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#597]
If you already scroll to the bottom of the page, switching chapters in quick switcher will update the news feed but keeps the scroll position.  The user will be at the bottom. It doesn't make sense.

**Comment by tasomaniac** [comment]
Now that we have a long list of events in the main page now, this became a problem with events as well. @lucasxas 

Scroll a lot, then change a chapter, the list starts from a random position.

**Comment by lucasxas** [comment]
This bug happens with all three tabs in the Home screen. 

If you swap Chapter, the scroll state of all tabs should return to the top

**Comment by lucasxas** [comment]
Argh, I spent a good couple of hours in this and I can't find a good solution. The problem here is that we're saving the state of the RecyclerView and even when we recreate the child fragments they get recreate with this saved state, thus the RecyclerView starts 'scrolled'.

If someone else wanna take a look, feel free to do so!

**Comment by tasomaniac** [comment]
We are using state saving ViewPagerAdapter. Maybe we should not update the adapter but recreate it from scratch when the chapter is changed.

**Comment by friedger** [comment]
Or attach the chapterid to the scroll position

Le 10 oct. 2016 12:06, "Said Tahsin Dane" <notifications@github.com> a
écrit :

**Comment by lucasxas** [comment]
I'll take a look at @tasomaniac's approach after I finish the EventDetail issue :)

**Comment by tasomaniac** [comment]
I've started on this [here](https://github.com/gdg-x/frisbee/tree/597/chapter_scroll_bug)

It works but I want to refactor a little bit more to make it look like better.
