### ISSUE TITLE
Fix inactive chapters click behavior in Pulse

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#599]
Here is the problem. The app gets the Pulse page from DevSite. Even if the chapter is not active, it is available in Pulse. This means that there are more chapters in Pulse than the main page. 

Mexico City is a good example to reproduce it today. 

When you click Mexico City in Pulse, it opens your default main page. The reason is that it cannot find it. Instead of this, we should warn user when we couldn't find it. 

It happens for very few of them but this is very confusing to the users.

**Comment by tasomaniac** [comment]
I've just looked at the devsite this morning, 

Mexico City is indeed listed as inactive. But the website can open and show it. 
https://developers.google.com/groups/chapter/111114679803991832261/

What should we do? Hub does not ingest inactive chapters.

**Comment by friedger** [comment]
In Pulse, a snackbar could be shown that no information are available for this chapter.

**Comment by friedger** [comment]
Inactive chapters are not defined by properties of the pulse object. Instead, here should be a check against the chapter directory whether the chapter is available locally. The hub only returns active chapters.

**Comment by friedger** [comment]
fixed by #641
