### ISSUE TITLE
People.load requires SCOPE_PLUS_LOGIN

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#613]
In https://github.com/gdg-x/frisbee/commit/f07e537ea28567309f307183eefc22d29c436694 the PLUS_LOGIN scope was removed. However, it is required by `People.load` used in Arrow.

Is the scope automatically included?

**Comment by tasomaniac** [comment]
Does it crash? I thought when we add setRequirePlus, it will add this.

The app is published to Beta, let's roll this back and publish again.

**Comment by friedger** [comment]
It looks like tagging is working as it should, so we can continue roll out.
