### ISSUE TITLE
Add Cardboard activity featuring photospheres of GDGs near you

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#626]
In the game section add a link to a card board activity that shows photospheres of GDG meetups.

The photospheres are managed by a CMS.

This was suggested by @mariobodemann to demonstrate GDGs at the Android conference droidcon in Berlin in June. He is willing to contribute.

**Comment by friedger** [comment]
Assigned to @mariobodemann

**Comment by tasomaniac** [comment]
Whaaaat? This is so cool.

**Comment by tasomaniac** [comment]
I am against adding backend related dependencies. For this we should somehow use our hub. We were already talking about moving hub to Firebase. If adding this feature to hub is not easy/possible, we can use Firebase. 

Keeping our setup process and dependencies sane is the most important priority for us right now.

**Comment by friedger** [comment]
Not planned anymore
