### ISSUE TITLE
Widget is not showing the next event

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#628]
Widget is not showing the next event (but the first one in the events list).

**Comment by evindj** [comment]
I got this solved but I am having hard times to create the pull request. I keep getting a 403 error when I try to push the commit. Any help?

**Comment by friedger** [comment]
Are you working on your own fork? Probably you do not have write
permission. You should fork on github and add the new repository as a new
remote url to your local git. Then push to that new remote repository. Then
create a pull request on github.com

Friedger
