### ISSUE TITLE
Migrate to Firebase Invites

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#637]
https://firebase.google.com/docs/invites/android

**Comment by friedger** [comment]
I started here: https://github.com/gdg-x/frisbee/tree/feature/637_invites

but run into an issue of Google Play services: https://github.com/firebase/quickstart-android/issues/42

**Comment by tasomaniac** [comment]
Hey, I saw in your branch you've integrated app invite links for events. That's a really good idea too. I would like to open a PR including those commits + mines. 

I am currently working on a separate screen in on boarding. I am planning to have an additional page on the first run if the user is invited by someone else. It will have a picture of the inviter and it will say welcome, you're invited by this person. What do you think? 

I'm almost done with technical stuff. I need design. I couldn't figure out how to display this info.
