### ISSUE TITLE
Remove all games API related features

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#648]
This issue is about deciding how to proceed with the different authentication APIs, i.e. Google Sign In and Games.

We propose to remove all the Games API related features, i.e. Arrow and Achievements because there is no clean way to maintain both Games and Sign-In.

We saw people having problems to login because the Google Games ID setup and the Google Plus authorisation confuses users.

This issue was written together with @tasomaniac .

**Comment by Splaktar** [comment]
I would raise this issue with the Google Games and Play Services teams. I would hate to lose the games features from the app. But I do understand that the APIs can be problematic.

**Comment by tasomaniac** [comment]
We actually tried to reach out to them. These changes actually improves UX in actual games. It kinda removes the friction for games when you setup it once. 
The response that I could get from Googlers was kinda just confirms our situation. They said it's unfortunately how it is. 
There are also no real non game app out there that uses game apis

**Comment by tasomaniac** [comment]
Fixed by #653

**Comment by tasomaniac** [comment]
Google recently announced that the new sign in API finally works for games. 

https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html

**Comment by friedger** [comment]
Too late..

Am 18.12.2016 18:33 schrieb "Said Tahsin Dane" <notifications@github.com>:

**Comment by tasomaniac** [comment]
😃
