### ISSUE TITLE
Ensure compatibility with chromebooks

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#649]
Currently, the app is not shown in Google Play on the Chromebook Flip.

**Comment by tasomaniac** [comment]
I don't know why Google is making this harder than it can be. 
I think we need to disable requirement of touch screen right?

**Comment by tasomaniac** [comment]
I had 1 crash on release 2.6.
I will create another release and it will include this fix. Can you later check on your chromebook if the app is visible? @friedger

**Comment by friedger** [comment]
will do!

**Comment by friedger** [comment]
It is still not compatible

**Comment by tasomaniac** [comment]
This new `untrackOld` made problems on Travis. Publish failed.
I reverted it. Working on the update right now.

**Comment by tasomaniac** [comment]
Released to 100% now. Should be live in couple of hours. Can you check again?

**Comment by friedger** [comment]
Is now available on the Chromebook



[image: --]
Friedger Müffke
[image: http://]about.me/friedger
<http://about.me/friedger>


2016-10-06 20:13 GMT+02:00 Said Tahsin Dane <notifications@github.com>:
