### ISSUE TITLE
Missing Cities

### ISSUE THREAD

**Issue by MichaelSolati** [gdg-x/frisbee#651]
I noticed earlier today that some cities (specifically Boston) are missing from the city drop down list in the app.

![content __com google android apps gsa velvet extradex extradexhostprovider_assist com google android apps gsa assist screenshotprovider_com google android apps gsa assist screenshotprovider_screenassistscreenshots_screenshot_20160815-112352](https://cloud.githubusercontent.com/assets/11811422/17669316/3bd713ea-62db-11e6-96cf-19407811819d.png)

**Comment by tasomaniac** [comment]
@MichaelSolati can it be because Boston is inactive? Only active cities are shown in the list.

**Comment by tasomaniac** [comment]
Hmmm actually, I double checked. Boston is shown in my app. Can you check again? It can be a server issue.

**Comment by MichaelSolati** [comment]
Server problem, it's showing up for me now. I was just surprised earlier when I didn't see it.
