### ISSUE TITLE
Links in Info page are not clickable. 

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#652]
Open GDG Tours page. Move to Info tab. Below organizers, the first link is clickable but the other links (e.g. Twitter, meetup) are not clickable.

**Comment by lucasxas** [comment]
Will take a look at this over the weekend.

**Comment by lucasxas** [comment]
I'm getting a 400 when trying to load that stuff though. Any ideas why? 
`{
                                                                      "error": {
                                                                       "errors": [
                                                                        {
                                                                         "domain": "usageLimits",
                                                                         "reason": "keyInvalid",
                                                                         "message": "Bad Request"
                                                                        }
                                                                       ],
                                                                       "code": 400,
                                                                       "message": "Bad Request"
                                                                      }
                                                                     }`

**Comment by tasomaniac** [comment]
We were using Googles java lib to do g+ requests. That took lots of method count and we removed it. 

We use an unbounded api token which is very restricted. 

We should use an api token which is limited by our app signature. We already have that in our BuildConfig. 

That is not working either because we are just using retrofit. I couldn't figure this out. :(

**Comment by lucasxas** [comment]
If I create one just to develop and don't commit/push it, will it work?

**Comment by tasomaniac** [comment]
Of course. Just in any project in Google console, try to produce and use an api key. 
It should be bound to signature. You can use our debug.keystore signature with debug packageid

**Comment by lucasxas** [comment]
Awesome.

**Comment by tasomaniac** [comment]
@lucasxas did you have something on this? If you had API keys issues, that's unfortunate. Maybe we can help you with that.

**Comment by lucasxas** [comment]
All good here @tasomaniac! I manage to get API key working and I'll give this bug a go today :)

**Comment by lucasxas** [comment]
Pull request open to fix this bug https://github.com/gdg-x/frisbee/pull/679

**Comment by lucasxas** [comment]
I noticed that the same bug happens with the links in the About section. The fix is the same, removing autoLink and adding MovementMethod, so I'll just fix it in the same PR.

**Comment by lucasxas** [comment]
Fixed in https://github.com/gdg-x/frisbee/pull/679
