### ISSUE TITLE
Upgrade App Invites

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#665]
The new Firebase App Invites uses Firebase Dynamic Links. They are really cool. They are just shortlink. Depending on the place you open it, it just does the best thing possible. 

More info here: https://firebase.google.com/docs/invites/

**Comment by tasomaniac** [comment]
@friedger I personally love this feature. Both since we have it in About screen, no body uses it. I am thinking to bring it to NavDrawer. What do you think?

**Comment by friedger** [comment]
There are a few other alternatives but for GDG lets go for Firebase App Invites.

**Comment by friedger** [comment]
NavDrawer sounds good to me.

**Comment by friedger** [comment]
See also https://github.com/gdg-x/frisbee/issues/637

This issue could be about moving only

**Comment by tasomaniac** [comment]
Oh I didn't know that we already have an issue about that. Let's use #637 to track
