### ISSUE TITLE
Widget does not have a button to enter the GDG app

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#68]
There should be an area to click to open the GDG app

**Comment by tasomaniac** [comment]
I think the best way to do this to open the event detail page in the app rather than directly openning the Google+ app. Easy and clean. Would you prefer doing that? @friedger 

Otherwise we need to change the design of the widget. I am sure that it is not used much.

**Comment by friedger** [comment]
Sounds good to me, I'll do it.


  [image: --]
Friedger Müffke
[image: http://]about.me/friedger
<http://about.me/friedger>


2015-05-04 21:38 GMT+02:00 Said Tahsin Dane <notifications@github.com>:
