### ISSUE TITLE
Project cannot be built successfully

### ISSUE THREAD

**Issue by giantthinker** [gdg-x/frisbee#680]
I am receiving this message `Error:(224, 0) Cause: repository not found: C:\Users\ABDELLAH_RAMADAN\Desktop\frisbee-develop`.

**Comment by friedger** [comment]
What command do you launch?
Can you open in Android Studio?

Please join us on gitter.im/gdg-x/frisbee

Closing this one.

**Comment by giantthinker** [comment]
Yes I do open in Android Studio before receiving the above message.
