### ISSUE TITLE
Unable to log into app

### ISSUE THREAD

**Issue by Intecpsp** [gdg-x/frisbee#722]
I'm getting "You're currently offline." And am unable to proceed past it. 

Pixel XL 2
Android 8.1.0
OPM2.171019.029

**Comment by Splaktar** [comment]
This is because the app depended upon the GDG-X Hub, but with the GDG program moving to Meetup, it wasn't feasible to continue to maintain the GDG-X Hub.

The Hub and this app have been retired 😞
